use super::Parm;
pub const DWD_202: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */ Parm("Seeg_peak", "jonswap parameter fm [s**(-1)]"),
    /* 2 */ Parm("Seeg_alpha", "jonswap parameter alpha [1]"),
    /* 3 */ Parm("Seeg_gamma", "jonswap parameter gamma [1]"),
    /* 4 */ Parm("Seeg_dir", "Seegang direction [degree true]"),
    /* 5 */ Parm("Seeg_energ", "Seegang energy densitiy [(m**2)*(s**2)]"),
    /* 6 */ Parm("Seeg_icemk", "Seegang ice mask [1]"),
    /* 7 */ Parm("peak p sw", "peak period of swell [s]"),
    /* 8 */ Parm("peak p ww", "peak period of wind waves [s]"),
    /* 9 */ Parm("var9", "undefined"),
    /* 10 */ Parm("var10", "undefined"),
    /* 11 */ Parm("var11", "undefined"),
    /* 12 */ Parm("var12", "undefined"),
    /* 13 */ Parm("var13", "undefined"),
    /* 14 */ Parm("var14", "undefined"),
    /* 15 */ Parm("var15", "undefined"),
    /* 16 */ Parm("var16", "undefined"),
    /* 17 */ Parm("var17", "undefined"),
    /* 18 */ Parm("var18", "undefined"),
    /* 19 */ Parm("var19", "undefined"),
    /* 20 */ Parm("Var. Geop.", "Varianz Geopotential [(m/s)**4]"),
    /* 21 */ Parm("Var. T", "Varianz Temperatur [K**2]"),
    /* 22 */ Parm("Var. u", "Varianz Zonalwind [(m/s)**2]"),
    /* 23 */ Parm("Var. v", "Varianz Meridionalwind [(m/s)**2]"),
    /* 24 */ Parm("Var. q", "Varianz spezifische Feuchte [(kg/kg)**2]"),
    /* 25 */ Parm("Mer. Imptr", "Meridionaler Impulstransport [(m/s)**2]"),
    /* 26 */
    Parm(
        "Mer. TrEpt",
        "Meridionaler Transport potentieller Energie [(m/s)**3]",
    ),
    /* 27 */
    Parm(
        "Mer. TrsW",
        "Meridionaler Transport sensibler Waerme [K*(m/s)]",
    ),
    /* 28 */
    Parm(
        "Mer. TrlW",
        "Meridionaler Transport latenter Waerme [(kg/kg)*(m/s)]",
    ),
    /* 29 */
    Parm(
        "Ver. TrEpt",
        "Vertikaler Transport potentieller Energie [(m/s)**2*(Pa/s)]",
    ),
    /* 30 */
    Parm(
        "Ver. TrsW",
        "Vertikaler Transport sensibler Waerme [K*(Pa/s)]",
    ),
    /* 31 */
    Parm(
        "Ver.TrlW",
        "Vertikaler Transport latenter Waerme [(kg/kg)*(Pa/s)]",
    ),
    /* 32 */ Parm("var32", "undefined"),
    /* 33 */ Parm("var33", "undefined"),
    /* 34 */ Parm("var34", "undefined"),
    /* 35 */ Parm("var35", "undefined"),
    /* 36 */ Parm("var36", "undefined"),
    /* 37 */ Parm("var37", "undefined"),
    /* 38 */ Parm("var38", "undefined"),
    /* 39 */ Parm("var39", "undefined"),
    /* 40 */
    Parm(
        "VarAF Geop",
        "Varianz des Analyse-Fehlers Geopotential [(m/s)**4]",
    ),
    /* 41 */
    Parm(
        "VarAF u",
        "Varianz des Analyse-Fehlers Zonalwind [(m/s)**2]",
    ),
    /* 42 */
    Parm(
        "VarAF v",
        "Varianz des Analyse-Fehlers Meridionalwind [(m/s)**2]",
    ),
    /* 43 */ Parm("var43", "undefined"),
    /* 44 */ Parm("DU_SSO", "undefined"),
    /* 45 */ Parm("DV_SSO", "undefined"),
    /* 46 */
    Parm(
        "SSO_STDH",
        "standard deviation of subgrid scale orogr. height [m]",
    ),
    /* 47 */ Parm("SSO_GAMMA", "anisotropy of topography [1]"),
    /* 48 */
    Parm(
        "SSO_THETA",
        "angle betw. principal axis of orogr. and global E [1]",
    ),
    /* 49 */ Parm("SSO_SIGMA", "mean slope of subgrid scale orography [1]"),
    /* 50 */ Parm("oro varian", "subgrid-scale variance of orography [m**2]"),
    /* 51 */
    Parm(
        "E-W oro va",
        "E-W component of subgrid-scale variance of orogr [m**2]",
    ),
    /* 52 */
    Parm(
        "N-S oro va",
        "N-S component of subgrid-scale variance of orogr [m**2]",
    ),
    /* 53 */
    Parm(
        "NW-SE o va",
        "NW-SE component of subgrid-scale variance of orogr [m**2]",
    ),
    /* 54 */
    Parm(
        "NE-SW o va",
        "NE-SW component of subgrid-scale variance of orogr [m**2]",
    ),
    /* 55 */ Parm("inl w frac", "fraction of inland water [1]"),
    /* 56 */ Parm("EMISS_RAD", "surface emissivity [1]"),
    /* 57 */ Parm("SOILTYP", "soil texture [1]"),
    /* 58 */ Parm("soil color", "soil color [1]"),
    /* 59 */ Parm("soil drain", "soil drainage [1]"),
    /* 60 */ Parm("ground wat", "ground water table [m]"),
    /* 61 */ Parm("LAI", "leaf area index [1]"),
    /* 62 */ Parm("ROOTDP", "root depth [m]"),
    /* 63 */ Parm("root dens", "root density [1]"),
    /* 64 */ Parm("HMO3", "height of maximum of ozone concentration [Pa]"),
    /* 65 */ Parm("VIO3", "total vertically integrated ozone content [Pa]"),
    /* 66 */ Parm("ld-sea msk", "land-sea mask [1]"),
    /* 67 */
    Parm(
        "PLCOV_MX",
        "ground fraction covered by plants (vegetation p.) [1]",
    ),
    /* 68 */
    Parm(
        "PLCOV_MN",
        "ground fraction covered by plants (time of rest) [1]",
    ),
    /* 69 */ Parm("LAI_MX", "leaf area index (vegetation period) [1]"),
    /* 70 */ Parm("LAI_MN", "leaf area index (time of rest) [1]"),
    /* 71 */ Parm("Orographie", "Orographie + Land-Meer-Verteilung [m]"),
    /* 72 */ Parm("r length m", "roughness length momentum [m]"),
    /* 73 */ Parm("r length h", "roughness length heat [m]"),
    /* 74 */ Parm("var smc", "variance of soil moisture content [kg**2/m**4]"),
    /* 75 */ Parm("FOR_E", "ground fraction covered by evergreen forest [1]"),
    /* 76 */ Parm("FOR_D", "ground fraction covered by deciduous forest [1]"),
    /* 77 */ Parm("NDVI", "normalized differential vegetation index [1]"),
    /* 78 */
    Parm(
        "NDVI_MAX",
        "annual max. of norm. differential vegetation index [1]",
    ),
    /* 79 */
    Parm(
        "NDVIRATIO",
        "proportion of act.value/max. norm.diff.veg.index [1]",
    ),
    /* 80 */ Parm("AER_SEA", "aerosol optical depth, type sea [1]"),
    /* 81 */ Parm("AER_LAN", "aerosol optical depth, type land [1]"),
    /* 82 */ Parm("AER_URB", "aerosol optical depth, type urban [1]"),
    /* 83 */ Parm("AER_DES", "aerosol optical depth, type desert [1]"),
    /* 84 */ Parm("var84", "undefined"),
    /* 85 */ Parm("var85", "undefined"),
    /* 86 */ Parm("var86", "undefined"),
    /* 87 */ Parm("var87", "undefined"),
    /* 88 */ Parm("var88", "undefined"),
    /* 89 */ Parm("var89", "undefined"),
    /* 90 */ Parm("var90", "undefined"),
    /* 91 */ Parm("var91", "undefined"),
    /* 92 */ Parm("var92", "undefined"),
    /* 93 */ Parm("var93", "undefined"),
    /* 94 */ Parm("var94", "undefined"),
    /* 95 */ Parm("var95", "undefined"),
    /* 96 */ Parm("var96", "undefined"),
    /* 97 */ Parm("var97", "undefined"),
    /* 98 */ Parm("var98", "undefined"),
    /* 99 */ Parm("var99", "undefined"),
    /* 100 */ Parm("var100", "undefined"),
    /* 101 */ Parm("tidal tend", "tidal tendencies [(m/s)**2]"),
    /* 102 */ Parm("diab heatg", "sum of diabatic heating terms [K/s]"),
    /* 103 */ Parm("adiab heat", "total adiabatic heating [K/s]"),
    /* 104 */
    Parm(
        "adv q tend",
        "advective tendency of specific humidity [s**(-1)]",
    ),
    /* 105 */
    Parm(
        "nadv q ten",
        "non-advective tendency of specific humidity [s**(-1)]",
    ),
    /* 106 */
    Parm(
        "adv m te X",
        "advective momentum tendency (X component) [m/s**2]",
    ),
    /* 107 */
    Parm(
        "adv m te Y",
        "advective momentum tendency (Y component) [m/s**2]",
    ),
    /* 108 */
    Parm(
        "nad m te X",
        "non-advective momentum tendency (X component) [m/s**2]",
    ),
    /* 109 */
    Parm(
        "nad m te Y",
        "non-advective momentum tendency (Y component) [m/s**2]",
    ),
    /* 110 */
    Parm(
        "torque",
        "sum of mountain and frictional torque [kg*(m/s)**2]",
    ),
    /* 111 */ Parm("budget val", "budget values [1]"),
    /* 112 */ Parm("scale fact", "scale factor [1]"),
    /* 113 */ Parm("FC", "Coriolis parameter [s**(-1)]"),
    /* 114 */ Parm("RLAT", "latitude [degr N]"),
    /* 115 */ Parm("RLON", "longitude [degr E]"),
    /* 116 */
    Parm(
        "relax fact",
        "relaxation factor (lateral boundary, LAM) [1]",
    ),
    /* 117 */
    Parm(
        "climsstint",
        "climatic sea surface temp interpolated in time [degr C]",
    ),
    /* 118 */ Parm("pot vortic", "potential vorticity [K*m**2/(s*kg)]"),
    /* 119 */ Parm("ln ps", "log surface pressure [1]"),
    /* 120 */ Parm("var120", "undefined"),
    /* 121 */ Parm("ZTD", "delay of the GPS signal through the atmosphere [m]"),
    /* 122 */
    Parm(
        "ZWD",
        "delay of the GPS signal through a wet atmosphere [m]",
    ),
    /* 123 */
    Parm(
        "ZHD",
        "delay of the GPS signal through a dry atmosphere [m]",
    ),
    /* 124 */ Parm("var124", "undefined"),
    /* 125 */ Parm("var125", "undefined"),
    /* 126 */ Parm("var126", "undefined"),
    /* 127 */ Parm("var127", "undefined"),
    /* 128 */ Parm("var128", "undefined"),
    /* 129 */ Parm("var129", "undefined"),
    /* 130 */ Parm("var130", "undefined"),
    /* 131 */ Parm("var131", "undefined"),
    /* 132 */ Parm("var132", "undefined"),
    /* 133 */ Parm("var133", "undefined"),
    /* 134 */ Parm("var134", "undefined"),
    /* 135 */ Parm("var135", "undefined"),
    /* 136 */ Parm("var136", "undefined"),
    /* 137 */ Parm("var137", "undefined"),
    /* 138 */ Parm("var138", "undefined"),
    /* 139 */ Parm("var139", "undefined"),
    /* 140 */ Parm("var140", "undefined"),
    /* 141 */ Parm("var141", "undefined"),
    /* 142 */ Parm("var142", "undefined"),
    /* 143 */ Parm("var143", "undefined"),
    /* 144 */ Parm("var144", "undefined"),
    /* 145 */ Parm("var145", "undefined"),
    /* 146 */ Parm("var146", "undefined"),
    /* 147 */ Parm("var147", "undefined"),
    /* 148 */ Parm("var148", "undefined"),
    /* 149 */ Parm("var149", "undefined"),
    /* 150 */ Parm("SO2-conc", "SO2-concentration [10**(-6)*g/m**3]"),
    /* 151 */ Parm("SO2-dryd", "SO2-dry deposition [10**(-3)*g/m**2]"),
    /* 152 */ Parm("SO2-wetd", "SO2-wet deposition [10**(-3)*g/m**2]"),
    /* 153 */ Parm("SO4-conc", "SO4-concentration [10**(-6)*g/m**3]"),
    /* 154 */ Parm("SO4-dryd", "SO4-dry deposition [10**(-3)*g/m**2]"),
    /* 155 */ Parm("SO4-wetd", "SO4-wet deposition [10**(-3)*g/m**2]"),
    /* 156 */ Parm("NO-conc", "NO-concentration [10**(-6)*g/m**3]"),
    /* 157 */ Parm("NO-dryd", "NO-dry deposition [10**(-3)*g/m**2]"),
    /* 158 */ Parm("NO-wetd", "NO-wet deposition [10**(-3)*g/m**2]"),
    /* 159 */ Parm("NO2-conc", "NO2-concentration [10**(-6)*g/m**3]"),
    /* 160 */ Parm("NO2-dryd", "NO2-dry deposition [10**(-3)*g/m**2]"),
    /* 161 */ Parm("NO2-wetd", "NO2-wet deposition [10**(-3)*g/m**2]"),
    /* 162 */ Parm("NO3-conc", "NO3-concentration [10**(-6)*g/m**3]"),
    /* 163 */ Parm("NO3-dryd", "NO3-dry deposition [10**(-3)*g/m**2]"),
    /* 164 */ Parm("NO3-wetd", "NO3-wet deposition [10**(-3)*g/m**2]"),
    /* 165 */ Parm("HNO3-conc", "HNO3-concentration [10**(-6)*g/m**3]"),
    /* 166 */ Parm("HNO3-dryd", "HNO3-dry deposition [10**(-3)*g/m**2]"),
    /* 167 */ Parm("HNO3-wetd", "HNO3-wet deposition [10**(-3)*g/m**2]"),
    /* 168 */ Parm("NH3-conc", "NH3-concentration [10**(-6)*g/m**3]"),
    /* 169 */ Parm("NH3-dryd", "NH3-dry deposition [10**(-3)*g/m**2]"),
    /* 170 */ Parm("NH3-wetd", "NH3-wet deposition [10**(-3)*g/m**2]"),
    /* 171 */ Parm("NH4-conc", "NH4-concentration [10**(-6)*g/m**3]"),
    /* 172 */ Parm("NH4-dryd", "NH4-dry deposition [10**(-3)*g/m**2]"),
    /* 173 */ Parm("NH4-wetd", "NH4-wet deposition [10**(-3)*g/m**2]"),
    /* 174 */ Parm("O3-conc", "O3-concentration [10**(-6)*g/m**3]"),
    /* 175 */ Parm("PAN-conc", "PAN-concentration [10**(-6)*g/m**3]"),
    /* 176 */ Parm("PAN-dryd", "PAN-dry deposition [10**(-3)*g/m**2]"),
    /* 177 */ Parm("OH-conc", "OH-concentration [10**(-6)*g/m**3]"),
    /* 178 */ Parm("O3-dryd", "O3-dry deposition [10**(-3)*g/m**2]"),
    /* 179 */ Parm("O3-wetd", "O3-wet deposition [10**(-3)*g/m**2]"),
    /* 180 */ Parm("O3", "O3-mixing ratio [kg/kg]"),
    /* 181 */ Parm("var181", "undefined"),
    /* 182 */ Parm("var182", "undefined"),
    /* 183 */ Parm("var183", "undefined"),
    /* 184 */ Parm("var184", "undefined"),
    /* 185 */ Parm("var185", "undefined"),
    /* 186 */ Parm("var186", "undefined"),
    /* 187 */ Parm("var187", "undefined"),
    /* 188 */ Parm("var188", "undefined"),
    /* 189 */ Parm("var189", "undefined"),
    /* 190 */ Parm("var190", "undefined"),
    /* 191 */ Parm("var191", "undefined"),
    /* 192 */ Parm("var192", "undefined"),
    /* 193 */ Parm("var193", "undefined"),
    /* 194 */ Parm("var194", "undefined"),
    /* 195 */ Parm("var195", "undefined"),
    /* 196 */ Parm("var196", "undefined"),
    /* 197 */ Parm("var197", "undefined"),
    /* 198 */ Parm("var198", "undefined"),
    /* 199 */ Parm("var199", "undefined"),
    /* 200 */ Parm("I131-conc", "I131-concentration [Bq/m**3]"),
    /* 201 */ Parm("I131-dryd", "I131-dry deposition [Bq/m**2]"),
    /* 202 */ Parm("I131-wetd", "I131-wet deposition [Bq/m**2]"),
    /* 203 */ Parm("Cs137-conc", "Cs137-concentration [Bq/m**3]"),
    /* 204 */ Parm("Cs137-dryd", "Cs1370dry deposition [Bq/m**2]"),
    /* 205 */ Parm("Cs137-wetd", "Cs137-wet deposition [Bq/m**2]"),
    /* 206 */ Parm("Te132-conc", "Te132-concentration [Bq/m**3]"),
    /* 207 */ Parm("Te132-dryd", "Te132-dry deposition [Bq/m**2]"),
    /* 208 */ Parm("Te132-wetd", "Te132-wet deposition [Bq/m**2]"),
    /* 209 */ Parm("Zr95-conc", "Zr95-concentration [Bq/m**3]"),
    /* 210 */ Parm("Zr95-dryd", "Zr95-dry deposition [Bq/m**2]"),
    /* 211 */ Parm("Zr95-wetd", "Zr95-wet deposition [Bq/m**2]"),
    /* 212 */ Parm("var212", "undefined"),
    /* 213 */ Parm("var213", "undefined"),
    /* 214 */ Parm("var214", "undefined"),
    /* 215 */ Parm("var215", "undefined"),
    /* 216 */ Parm("var216", "undefined"),
    /* 217 */ Parm("var217", "undefined"),
    /* 218 */ Parm("var218", "undefined"),
    /* 219 */ Parm("var219", "undefined"),
    /* 220 */ Parm("var220", "undefined"),
    /* 221 */ Parm("var221", "undefined"),
    /* 222 */ Parm("var222", "undefined"),
    /* 223 */ Parm("var223", "undefined"),
    /* 224 */ Parm("var224", "undefined"),
    /* 225 */ Parm("var225", "undefined"),
    /* 226 */ Parm("var226", "undefined"),
    /* 227 */ Parm("var227", "undefined"),
    /* 228 */ Parm("var228", "undefined"),
    /* 229 */ Parm("var229", "undefined"),
    /* 230 */ Parm("var230", "undefined"),
    /* 231 */
    Parm(
        "USTR_SSO",
        "Mom. flux, u component, due to SSO-effects [(N/(m**2)]",
    ),
    /* 232 */
    Parm(
        "VSTR_SSO",
        "Mom. flux, v component, due to SSO-effects [(N/(m**2)]",
    ),
    /* 233 */
    Parm(
        "VDIS_SSO",
        "Dissipation of kinetic energy due to SSO-effects [(W/(m**2)]",
    ),
    /* 234 */ Parm("var234", "undefined"),
    /* 235 */ Parm("var235", "undefined"),
    /* 236 */ Parm("var236", "undefined"),
    /* 237 */ Parm("var237", "undefined"),
    /* 238 */ Parm("var238", "undefined"),
    /* 239 */ Parm("var239", "undefined"),
    /* 240 */
    Parm(
        "UV_Ind_F_h",
        "UV_Index corr. for albedo+altitude,cloudless(F), h [1]",
    ),
    /* 241 */
    Parm(
        "BasicUV_IF",
        "Basic UV_Index m.s.l.,fixed albedo,cloudless(F), h [1]",
    ),
    /* 242 */
    Parm(
        "UV_Ind_W_h",
        "UV_Index corrected for albedo+altitude+clouds(W),h [1]",
    ),
    /* 243 */ Parm("UV_IndmaxF", "UV_Index cloudless (F), daily maximum [1]"),
    /* 244 */ Parm("SB-Index", "Sonnenbrand-Index [(W*10**(-3))/m**2]"),
    /* 245 */
    Parm(
        "SB-Index W",
        "Sonnenbrand-Index bei mittl. Bewoelkung (08z-12z) [(W*10**(-3))/m**2]",
    ),
    /* 246 */
    Parm(
        "Kan.UVB-WI",
        "Kanadischer UVB-Warnindex (bew|lkungsreduziert) [(W*10**(-3))/m**2]",
    ),
    /* 247 */
    Parm(
        "gesamt O3",
        "total column ozone (Gesamtozon) [Dobson Unit, DU]",
    ),
    /* 248 */ Parm("UV_IndmaxW", "UV_Index clouded (W), daily maximum [1]"),
    /* 249 */ Parm("h UV_IndMx", "time of UV_Index maximum [h UTC]"),
    /* 250 */ Parm("var250", "undefined"),
    /* 251 */ Parm("var251", "undefined"),
    /* 252 */ Parm("var252", "undefined"),
    /* 253 */ Parm("var253", "undefined"),
    /* 254 */ Parm("var254", "undefined"),
    /* 255 */ Parm("var255", "undefined"),
];
