use super::Parm;
pub const ECMWF_162: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */ Parm("var1", "undefined"),
    /* 2 */ Parm("var2", "undefined"),
    /* 3 */ Parm("var3", "undefined"),
    /* 4 */ Parm("var4", "undefined"),
    /* 5 */ Parm("var5", "undefined"),
    /* 6 */ Parm("var6", "undefined"),
    /* 7 */ Parm("var7", "undefined"),
    /* 8 */ Parm("var8", "undefined"),
    /* 9 */ Parm("var9", "undefined"),
    /* 10 */ Parm("var10", "undefined"),
    /* 11 */ Parm("var11", "undefined"),
    /* 12 */ Parm("var12", "undefined"),
    /* 13 */ Parm("var13", "undefined"),
    /* 14 */ Parm("var14", "undefined"),
    /* 15 */ Parm("var15", "undefined"),
    /* 16 */ Parm("var16", "undefined"),
    /* 17 */ Parm("var17", "undefined"),
    /* 18 */ Parm("var18", "undefined"),
    /* 19 */ Parm("var19", "undefined"),
    /* 20 */ Parm("var20", "undefined"),
    /* 21 */ Parm("var21", "undefined"),
    /* 22 */ Parm("var22", "undefined"),
    /* 23 */ Parm("var23", "undefined"),
    /* 24 */ Parm("var24", "undefined"),
    /* 25 */ Parm("var25", "undefined"),
    /* 26 */ Parm("var26", "undefined"),
    /* 27 */ Parm("var27", "undefined"),
    /* 28 */ Parm("var28", "undefined"),
    /* 29 */ Parm("var29", "undefined"),
    /* 30 */ Parm("var30", "undefined"),
    /* 31 */ Parm("var31", "undefined"),
    /* 32 */ Parm("var32", "undefined"),
    /* 33 */ Parm("var33", "undefined"),
    /* 34 */ Parm("var34", "undefined"),
    /* 35 */ Parm("var35", "undefined"),
    /* 36 */ Parm("var36", "undefined"),
    /* 37 */ Parm("var37", "undefined"),
    /* 38 */ Parm("var38", "undefined"),
    /* 39 */ Parm("var39", "undefined"),
    /* 40 */ Parm("var40", "undefined"),
    /* 41 */ Parm("var41", "undefined"),
    /* 42 */ Parm("var42", "undefined"),
    /* 43 */ Parm("var43", "undefined"),
    /* 44 */ Parm("var44", "undefined"),
    /* 45 */ Parm("var45", "undefined"),
    /* 46 */ Parm("var46", "undefined"),
    /* 47 */ Parm("var47", "undefined"),
    /* 48 */ Parm("var48", "undefined"),
    /* 49 */ Parm("var49", "undefined"),
    /* 50 */ Parm("var50", "undefined"),
    /* 51 */ Parm("var51", "Surface geopotential [m**2 s**-2]"),
    /* 52 */ Parm("var52", "Surface pressure [Pa]"),
    /* 53 */
    Parm(
        "var53",
        "Vertical integral of mass of atmosphere [kg m**-2]",
    ),
    /* 54 */ Parm("var54", "Vertical integral of temperature [K kg m**-2]"),
    /* 55 */
    Parm(
        "var55",
        "Vertical integral of total column water vapour [kg m**-2]",
    ),
    /* 56 */
    Parm(
        "var56",
        "Vertical integral of total column liquid cloud water [kg m**-2]",
    ),
    /* 57 */
    Parm(
        "var57",
        "Vertical integral of total column frozen cloud water [kg m**-2]",
    ),
    /* 58 */
    Parm(
        "var58",
        "Vertical integral of total column ozone [kg m**-2]",
    ),
    /* 59 */ Parm("var59", "Vertical integral of kinetic energy [J m**-2]"),
    /* 60 */ Parm("var60", "Vertical integral of thermal energy [J m**-2]"),
    /* 61 */ Parm("var61", "Vertical integral of dry static energy [J m**-2]"),
    /* 62 */
    Parm(
        "var62",
        "Vertical integral of moist static energy [J m**-2]",
    ),
    /* 63 */ Parm("var63", "Vertical integral of total energy [J m**-2]"),
    /* 64 */ Parm("var64", "Vertical integral of energy conversion [W m**-2]"),
    /* 65 */
    Parm(
        "var65",
        "Vertical integral of eastward mass flux [kg m**-1 s**-1]",
    ),
    /* 66 */
    Parm(
        "var66",
        "Vertical integral of northward mass flux [kg m**-1 s**-1]",
    ),
    /* 67 */
    Parm(
        "var67",
        "Vertical integral of eastward kinetic energy flux [W m**-2]",
    ),
    /* 68 */
    Parm(
        "var68",
        "Vertical integral of northward kinetic energy flux [W m**-2]",
    ),
    /* 69 */ Parm("var69", "Vertical integral of eastward heat flux [W m**-2]"),
    /* 70 */
    Parm(
        "var70",
        "Vertical integral of northward heat flux [W m**-2]",
    ),
    /* 71 */
    Parm(
        "var71",
        "Vertical integral of eastward water vapour flux [kg m**-1 s**-1]",
    ),
    /* 72 */
    Parm(
        "var72",
        "Vertical integral of northward water vapour flux [kg m**-1 s**-1]",
    ),
    /* 73 */
    Parm(
        "var73",
        "Vertical integral of eastward geopotential flux [W m**-2]",
    ),
    /* 74 */
    Parm(
        "var74",
        "Vertical integral of northward geopotential flux [W m**-2]",
    ),
    /* 75 */
    Parm(
        "var75",
        "Vertical integral of eastward total energy flux [W m**-2]",
    ),
    /* 76 */
    Parm(
        "var76",
        "Vertical integral of northward total energy flux [W m**-2]",
    ),
    /* 77 */
    Parm(
        "var77",
        "Vertical integral of eastward ozone flux [kg m**-1 s**-1]",
    ),
    /* 78 */
    Parm(
        "var78",
        "Vertical integral of northward ozone flux [kg m**-1 s**-1]",
    ),
    /* 79 */ Parm("var79", "undefined"),
    /* 80 */ Parm("var80", "undefined"),
    /* 81 */
    Parm(
        "var81",
        "Vertical integral of divergence of mass flux [kg m**-2 s**-1]",
    ),
    /* 82 */
    Parm(
        "var82",
        "Vertical integral of divergence of kinetic energy flux [W m**-2]",
    ),
    /* 83 */
    Parm(
        "var83",
        "Vertical integral of divergence of thermal energy flux [W m**-2]",
    ),
    /* 84 */
    Parm(
        "var84",
        "Vertical integral of divergence of moisture flux [kg m**-2 s**-1]",
    ),
    /* 85 */
    Parm(
        "var85",
        "Vertical integral of divergence of geopotential flux [W m**-2]",
    ),
    /* 86 */
    Parm(
        "var86",
        "Vertical integral of divergence of total energy flux [W m**-2]",
    ),
    /* 87 */
    Parm(
        "var87",
        "Vertical integral of divergence of ozone flux [kg m**-2 s**-1]",
    ),
    /* 88 */ Parm("var88", "undefined"),
    /* 89 */ Parm("var89", "undefined"),
    /* 90 */ Parm("var90", "undefined"),
    /* 91 */ Parm("var91", "undefined"),
    /* 92 */ Parm("var92", "undefined"),
    /* 93 */ Parm("var93", "undefined"),
    /* 94 */ Parm("var94", "undefined"),
    /* 95 */ Parm("var95", "undefined"),
    /* 96 */ Parm("var96", "undefined"),
    /* 97 */ Parm("var97", "undefined"),
    /* 98 */ Parm("var98", "undefined"),
    /* 99 */ Parm("var99", "undefined"),
    /* 100 */ Parm("var100", "Tendency of short wave radiation [K]"),
    /* 101 */ Parm("var101", "Tendency of long wave radiation [K]"),
    /* 102 */ Parm("var102", "Tendency of clear sky short wave radiation [K]"),
    /* 103 */ Parm("var103", "Tendency of clear sky long wave radiation [K]"),
    /* 104 */ Parm("var104", "Updraught mass flux [kg m**-2]"),
    /* 105 */ Parm("var105", "Downdraught mass flux [kg m**-2]"),
    /* 106 */ Parm("var106", "Updraught detrainment rate [kg m**-3]"),
    /* 107 */ Parm("var107", "Downdraught detrainment rate [kg m**-3]"),
    /* 108 */ Parm("var108", "Total precipitation flux [kg m**-2]"),
    /* 109 */ Parm("var109", "Turbulent diffusion coefficient for heat [m**2]"),
    /* 110 */ Parm("var110", "Tendency of temperature due to physics [K]"),
    /* 111 */
    Parm(
        "var111",
        "Tendency of specific humidity due to physics [kg kg**-1]",
    ),
    /* 112 */ Parm("var112", "Tendency of u component due to physics [m s**-1]"),
    /* 113 */ Parm("var113", "Tendency of v component due to physics [m s**-1]"),
    /* 114 */ Parm("var114", "undefined"),
    /* 115 */ Parm("var115", "undefined"),
    /* 116 */ Parm("var116", "undefined"),
    /* 117 */ Parm("var117", "undefined"),
    /* 118 */ Parm("var118", "undefined"),
    /* 119 */ Parm("var119", "undefined"),
    /* 120 */ Parm("var120", "undefined"),
    /* 121 */ Parm("var121", "undefined"),
    /* 122 */ Parm("var122", "undefined"),
    /* 123 */ Parm("var123", "undefined"),
    /* 124 */ Parm("var124", "undefined"),
    /* 125 */ Parm("var125", "undefined"),
    /* 126 */ Parm("var126", "undefined"),
    /* 127 */ Parm("var127", "undefined"),
    /* 128 */ Parm("var128", "undefined"),
    /* 129 */ Parm("var129", "undefined"),
    /* 130 */ Parm("var130", "undefined"),
    /* 131 */ Parm("var131", "undefined"),
    /* 132 */ Parm("var132", "undefined"),
    /* 133 */ Parm("var133", "undefined"),
    /* 134 */ Parm("var134", "undefined"),
    /* 135 */ Parm("var135", "undefined"),
    /* 136 */ Parm("var136", "undefined"),
    /* 137 */ Parm("var137", "undefined"),
    /* 138 */ Parm("var138", "undefined"),
    /* 139 */ Parm("var139", "undefined"),
    /* 140 */ Parm("var140", "undefined"),
    /* 141 */ Parm("var141", "undefined"),
    /* 142 */ Parm("var142", "undefined"),
    /* 143 */ Parm("var143", "undefined"),
    /* 144 */ Parm("var144", "undefined"),
    /* 145 */ Parm("var145", "undefined"),
    /* 146 */ Parm("var146", "undefined"),
    /* 147 */ Parm("var147", "undefined"),
    /* 148 */ Parm("var148", "undefined"),
    /* 149 */ Parm("var149", "undefined"),
    /* 150 */ Parm("var150", "undefined"),
    /* 151 */ Parm("var151", "undefined"),
    /* 152 */ Parm("var152", "undefined"),
    /* 153 */ Parm("var153", "undefined"),
    /* 154 */ Parm("var154", "undefined"),
    /* 155 */ Parm("var155", "undefined"),
    /* 156 */ Parm("var156", "undefined"),
    /* 157 */ Parm("var157", "undefined"),
    /* 158 */ Parm("var158", "undefined"),
    /* 159 */ Parm("var159", "undefined"),
    /* 160 */ Parm("var160", "undefined"),
    /* 161 */ Parm("var161", "undefined"),
    /* 162 */ Parm("var162", "undefined"),
    /* 163 */ Parm("var163", "undefined"),
    /* 164 */ Parm("var164", "undefined"),
    /* 165 */ Parm("var165", "undefined"),
    /* 166 */ Parm("var166", "undefined"),
    /* 167 */ Parm("var167", "undefined"),
    /* 168 */ Parm("var168", "undefined"),
    /* 169 */ Parm("var169", "undefined"),
    /* 170 */ Parm("var170", "undefined"),
    /* 171 */ Parm("var171", "undefined"),
    /* 172 */ Parm("var172", "undefined"),
    /* 173 */ Parm("var173", "undefined"),
    /* 174 */ Parm("var174", "undefined"),
    /* 175 */ Parm("var175", "undefined"),
    /* 176 */ Parm("var176", "undefined"),
    /* 177 */ Parm("var177", "undefined"),
    /* 178 */ Parm("var178", "undefined"),
    /* 179 */ Parm("var179", "undefined"),
    /* 180 */ Parm("var180", "undefined"),
    /* 181 */ Parm("var181", "undefined"),
    /* 182 */ Parm("var182", "undefined"),
    /* 183 */ Parm("var183", "undefined"),
    /* 184 */ Parm("var184", "undefined"),
    /* 185 */ Parm("var185", "undefined"),
    /* 186 */ Parm("var186", "undefined"),
    /* 187 */ Parm("var187", "undefined"),
    /* 188 */ Parm("var188", "undefined"),
    /* 189 */ Parm("var189", "undefined"),
    /* 190 */ Parm("var190", "undefined"),
    /* 191 */ Parm("var191", "undefined"),
    /* 192 */ Parm("var192", "undefined"),
    /* 193 */ Parm("var193", "undefined"),
    /* 194 */ Parm("var194", "undefined"),
    /* 195 */ Parm("var195", "undefined"),
    /* 196 */ Parm("var196", "undefined"),
    /* 197 */ Parm("var197", "undefined"),
    /* 198 */ Parm("var198", "undefined"),
    /* 199 */ Parm("var199", "undefined"),
    /* 200 */ Parm("var200", "undefined"),
    /* 201 */ Parm("var201", "undefined"),
    /* 202 */ Parm("var202", "undefined"),
    /* 203 */ Parm("var203", "undefined"),
    /* 204 */ Parm("var204", "undefined"),
    /* 205 */ Parm("var205", "undefined"),
    /* 206 */ Parm("var206", "Variance of geopotential [m**4 s**-4]"),
    /* 207 */
    Parm(
        "var207",
        "Covariance of geopotential/temperature [m**2 K s**-2]",
    ),
    /* 208 */ Parm("var208", "Variance of temperature [K**2]"),
    /* 209 */
    Parm(
        "var209",
        "Covariance of geopotential/specific humidity [m**2 s**-2]",
    ),
    /* 210 */ Parm("var210", "Covariance of temperature/specific humidity [K]"),
    /* 211 */ Parm("var211", "Variance of specific humidity []"),
    /* 212 */
    Parm(
        "var212",
        "Covariance of u component/geopotential [M**3 s**-3]",
    ),
    /* 213 */
    Parm(
        "var213",
        "Covariance of u component/temperature [m s**-1 K]",
    ),
    /* 214 */
    Parm(
        "var214",
        "Covariance of u component/specific humidity [m s**-1]",
    ),
    /* 215 */ Parm("var215", "Variance of u component [m**2 s**-2]"),
    /* 216 */
    Parm(
        "var216",
        "Covariance of v component/geopotential [M**3 s**-3]",
    ),
    /* 217 */ Parm("var217", "Covariance of v component/temperaure [m s**-1 K]"),
    /* 218 */
    Parm(
        "var218",
        "Covariance of v component/specific humidity [m s**-1]",
    ),
    /* 219 */
    Parm(
        "var219",
        "Covariance of v component/u component [m**2 s**-2]",
    ),
    /* 220 */ Parm("var220", "Variance of v component [m**2 s**-2]"),
    /* 221 */ Parm("var221", "Covariance of omega/geopotential [m**2 Pa s**-3]"),
    /* 222 */ Parm("var222", "Covariance of omega/temperature [Pa s**-1 K]"),
    /* 223 */ Parm("var223", "Covariance of omega/specific humidity [Pa s**-1]"),
    /* 224 */ Parm("var224", "Covariance of omega/u component [m Pa s**-2]"),
    /* 225 */ Parm("var225", "Covariance of omega/v component [m Pa s**-2]"),
    /* 226 */ Parm("var226", "Variance of omega [Pa**2 s**-2]"),
    /* 227 */ Parm("var227", "Variance of surface pressure [Pa**2]"),
    /* 228 */ Parm("var228", "undefined"),
    /* 229 */ Parm("var229", "Variance of relative humidity [dimensionless]"),
    /* 230 */ Parm("var230", "Covariance of u component/ozone [m s**-1]"),
    /* 231 */ Parm("var231", "Covariance of v component/ozone [m s**-1]"),
    /* 232 */ Parm("var232", "Covariance of omega/ozone [Pa s**-1]"),
    /* 233 */ Parm("var233", "Variance of ozone [dimensionless]"),
    /* 234 */ Parm("var234", "undefined"),
    /* 235 */ Parm("var235", "undefined"),
    /* 236 */ Parm("var236", "undefined"),
    /* 237 */ Parm("var237", "undefined"),
    /* 238 */ Parm("var238", "undefined"),
    /* 239 */ Parm("var239", "undefined"),
    /* 240 */ Parm("var240", "undefined"),
    /* 241 */ Parm("var241", "undefined"),
    /* 242 */ Parm("var242", "undefined"),
    /* 243 */ Parm("var243", "undefined"),
    /* 244 */ Parm("var244", "undefined"),
    /* 245 */ Parm("var245", "undefined"),
    /* 246 */ Parm("var246", "undefined"),
    /* 247 */ Parm("var247", "undefined"),
    /* 248 */ Parm("var248", "undefined"),
    /* 249 */ Parm("var249", "undefined"),
    /* 250 */ Parm("var250", "undefined"),
    /* 251 */ Parm("var251", "undefined"),
    /* 252 */ Parm("var252", "undefined"),
    /* 253 */ Parm("var253", "undefined"),
    /* 254 */ Parm("var254", "undefined"),
    /* 255 */ Parm("var255", "Indicates a missing value []"),
];
