use super::Parm;
pub const ECMWF_210: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */
    Parm(
        "AERMR01",
        "Sea Salt Aerosol (0.03 - 0.5 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 2 */
    Parm(
        "AERMR02",
        "Sea Salt Aerosol (0.5 - 5 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 3 */
    Parm(
        "AERMR03",
        "Sea Salt Aerosol (5 - 20 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 4 */
    Parm(
        "AERMR04",
        "Dust Aerosol (0.03 - 0.55 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 5 */
    Parm(
        "AERMR05",
        "Dust Aerosol (0.55 - 0.9 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 6 */
    Parm(
        "AERMR06",
        "Dust Aerosol (0.9 - 20 um) Mixing Ratio [kg kg**-1]",
    ),
    /* 7 */
    Parm(
        "AERMR07",
        "Hydrophobic Organic Matter Aerosol Mixing Ratio [kg kg**-1]",
    ),
    /* 8 */
    Parm(
        "AERMR08",
        "Hydrophilic Organic Matter Aerosol Mixing Ratio [kg kg**-1]",
    ),
    /* 9 */
    Parm(
        "AERMR09",
        "Hydrophobic Black Carbon Aerosol Mixing Ratio [kg kg**-1]",
    ),
    /* 10 */
    Parm(
        "AERMR10",
        "Hydrophilic Black Carbon Aerosol Mixing Ratio [kg kg**-1]",
    ),
    /* 11 */ Parm("AERMR11", "Sulphate Aerosol Mixing Ratio [kg kg**-1]"),
    /* 12 */ Parm("AERMR12", "Aerosol type 12 mixing ratio [kg kg**-1]"),
    /* 13 */ Parm("var13", "undefined"),
    /* 14 */ Parm("var14", "undefined"),
    /* 15 */ Parm("var15", "undefined"),
    /* 16 */
    Parm(
        "AERGN01",
        "Aerosol type 1 source/gain accumulated [kg m**-2]",
    ),
    /* 17 */
    Parm(
        "AERGN02",
        "Aerosol type 2 source/gain accumulated [kg m**-2]",
    ),
    /* 18 */
    Parm(
        "AERGN03",
        "Aerosol type 3 source/gain accumulated [kg m**-2]",
    ),
    /* 19 */
    Parm(
        "AERGN04",
        "Aerosol type 4 source/gain accumulated [kg m**-2]",
    ),
    /* 20 */
    Parm(
        "AERGN05",
        "Aerosol type 5 source/gain accumulated [kg m**-2]",
    ),
    /* 21 */
    Parm(
        "AERGN06",
        "Aerosol type 6 source/gain accumulated [kg m**-2]",
    ),
    /* 22 */
    Parm(
        "AERGN07",
        "Aerosol type 7 source/gain accumulated [kg m**-2]",
    ),
    /* 23 */
    Parm(
        "AERGN08",
        "Aerosol type 8 source/gain accumulated [kg m**-2]",
    ),
    /* 24 */
    Parm(
        "AERGN09",
        "Aerosol type 9 source/gain accumulated [kg m**-2]",
    ),
    /* 25 */
    Parm(
        "AERGN10",
        "Aerosol type 10 source/gain accumulated [kg m**-2]",
    ),
    /* 26 */
    Parm(
        "AERGN11",
        "Aerosol type 11 source/gain accumulated [kg m**-2]",
    ),
    /* 27 */
    Parm(
        "AERGN12",
        "Aerosol type 12 source/gain accumulated [kg m**-2]",
    ),
    /* 28 */ Parm("var28", "undefined"),
    /* 29 */ Parm("var29", "undefined"),
    /* 30 */ Parm("var30", "undefined"),
    /* 31 */ Parm("AERLS01", "Aerosol type 1 sink/loss accumulated [kg m**-2]"),
    /* 32 */ Parm("AERLS02", "Aerosol type 2 sink/loss accumulated [kg m**-2]"),
    /* 33 */ Parm("AERLS03", "Aerosol type 3 sink/loss accumulated [kg m**-2]"),
    /* 34 */ Parm("AERLS04", "Aerosol type 4 sink/loss accumulated [kg m**-2]"),
    /* 35 */ Parm("AERLS05", "Aerosol type 5 sink/loss accumulated [kg m**-2]"),
    /* 36 */ Parm("AERLS06", "Aerosol type 6 sink/loss accumulated [kg m**-2]"),
    /* 37 */ Parm("AERLS07", "Aerosol type 7 sink/loss accumulated [kg m**-2]"),
    /* 38 */ Parm("AERLS08", "Aerosol type 8 sink/loss accumulated [kg m**-2]"),
    /* 39 */ Parm("AERLS09", "Aerosol type 9 sink/loss accumulated [kg m**-2]"),
    /* 40 */
    Parm(
        "AERLS10",
        "Aerosol type 10 sink/loss accumulated [kg m**-2]",
    ),
    /* 41 */
    Parm(
        "AERLS11",
        "Aerosol type 11 sink/loss accumulated [kg m**-2]",
    ),
    /* 42 */
    Parm(
        "AERLS12",
        "Aerosol type 12 sink/loss accumulated [kg m**-2]",
    ),
    /* 43 */ Parm("var43", "undefined"),
    /* 44 */ Parm("var44", "undefined"),
    /* 45 */ Parm("var45", "undefined"),
    /* 46 */ Parm("AERPR", "Aerosol precursor mixing ratio [kg kg**-1]"),
    /* 47 */ Parm("AERSM", "Aerosol small mode mixing ratio [kg kg**-1]"),
    /* 48 */ Parm("AERLG", "Aerosol large mode mixing ratio [kg kg**-1]"),
    /* 49 */ Parm("AODPR", "Aerosol precursor optical depth [dimensionless]"),
    /* 50 */ Parm("AODSM", "Aerosol small mode optical depth [dimensionless]"),
    /* 51 */ Parm("AODLG", "Aerosol large mode optical depth [dimensionless]"),
    /* 52 */ Parm("AERDEP", "Dust emission potential [kg s**2 m**-5]"),
    /* 53 */ Parm("AERLTS", "Lifting threshold speed [m s**-1]"),
    /* 54 */ Parm("AERSCC", "Soil clay content [%]"),
    /* 55 */ Parm("var55", "undefined"),
    /* 56 */ Parm("var56", "undefined"),
    /* 57 */ Parm("var57", "undefined"),
    /* 58 */ Parm("var58", "undefined"),
    /* 59 */ Parm("var59", "undefined"),
    /* 60 */ Parm("var60", "undefined"),
    /* 61 */ Parm("CO2", "Carbon Dioxide [kg kg**-1]"),
    /* 62 */ Parm("CH4", "Methane [kg kg**-1]"),
    /* 63 */ Parm("N2O", "Nitrous oxide [kg kg**-1]"),
    /* 64 */ Parm("TCCO2", "Total column Carbon Dioxide [kg m**-2]"),
    /* 65 */ Parm("TCCH4", "Total column Methane [kg m**-2]"),
    /* 66 */ Parm("TCN2O", "Total column Nitrous oxide [kg m**-2]"),
    /* 67 */ Parm("CO2OF", "Ocean flux of Carbon Dioxide [kg m**-2 s**-1]"),
    /* 68 */
    Parm(
        "CO2NBF",
        "Natural biosphere flux of Carbon Dioxide [kg m**-2 s**-1]",
    ),
    /* 69 */
    Parm(
        "CO2APF",
        "Anthropogenic emissions of Carbon Dioxide [kg m**-2 s**-1]",
    ),
    /* 70 */ Parm("CH4F", "Methane Surface Fluxes [kg m**-2 s**-1]"),
    /* 71 */
    Parm(
        "kCH4",
        "Methane loss rate due to radical hydroxyl (OH) [s**-1]",
    ),
    /* 72 */ Parm("var72", "undefined"),
    /* 73 */ Parm("var73", "undefined"),
    /* 74 */ Parm("var74", "undefined"),
    /* 75 */ Parm("var75", "undefined"),
    /* 76 */ Parm("var76", "undefined"),
    /* 77 */ Parm("var77", "undefined"),
    /* 78 */ Parm("var78", "undefined"),
    /* 79 */ Parm("var79", "undefined"),
    /* 80 */
    Parm(
        "CO2FIRE",
        "Wildfire flux of Carbon Dioxide [kg m**-2 s**-1]",
    ),
    /* 81 */
    Parm(
        "COFIRE",
        "Wildfire flux of Carbon Monoxide [kg m**-2 s**-1]",
    ),
    /* 82 */ Parm("CH4FIRE", "Wildfire flux of Methane [kg m**-2 s**-1]"),
    /* 83 */
    Parm(
        "NMHCFIRE",
        "Wildfire flux of Non-Methane Hydro-Carbons [kg m**-2 s**-1]",
    ),
    /* 84 */ Parm("H2FIRE", "Wildfire flux of Hydrogen [kg m**-2 s**-1]"),
    /* 85 */
    Parm(
        "NOXFIRE",
        "Wildfire flux of Nitrogen Oxides NOx [kg m**-2 s**-1]",
    ),
    /* 86 */ Parm("N2OFIRE", "Wildfire flux of Nitrous Oxide [kg m**-2 s**-1]"),
    /* 87 */
    Parm(
        "PM2P5FIRE",
        "Wildfire flux of Particulate Matter PM2.5 [kg m**-2 s**-1]",
    ),
    /* 88 */
    Parm(
        "TPMFIRE",
        "Wildfire flux of Total Particulate Matter [kg m**-2 s**-1]",
    ),
    /* 89 */
    Parm(
        "TCFIRE",
        "Wildfire flux of Total Carbon in Aerosols [kg m**-2 s**-1]",
    ),
    /* 90 */ Parm("OCFIRE", "Wildfire flux of Organic Carbon [kg m**-2 s**-1]"),
    /* 91 */ Parm("BCFIRE", "Wildfire flux of Black Carbon [kg m**-2 s**-1]"),
    /* 92 */
    Parm(
        "CFIRE",
        "Wildfire overall flux of burnt Carbon [kg m**-2 s**-1]",
    ),
    /* 93 */ Parm("C4FFIRE", "Wildfire fraction of C4 plants [dimensionless]"),
    /* 94 */ Parm("VEGFIRE", "Wildfire vegetation map index [dimensionless]"),
    /* 95 */ Parm("CCFIRE", "Wildfire Combustion Completeness [dimensionless]"),
    /* 96 */ Parm("FLFIRE", "Wildfire Fuel Load"),
    /* 97 */ Parm("BFFIRE", "Wildfire fraction of area burnt [dimensionless]"),
    /* 98 */ Parm("OAFIRE", "Wildfire observed area [m**2]"),
    /* 99 */ Parm("FRPFIRE", "Wildfire radiative power [W m**-2]"),
    /* 100 */ Parm("CRFIRE", "Wildfire combustion rate [kg m**-2 s**-1]"),
    /* 101 */ Parm("var101", "undefined"),
    /* 102 */ Parm("var102", "undefined"),
    /* 103 */ Parm("var103", "undefined"),
    /* 104 */ Parm("var104", "undefined"),
    /* 105 */ Parm("var105", "undefined"),
    /* 106 */ Parm("var106", "undefined"),
    /* 107 */ Parm("var107", "undefined"),
    /* 108 */ Parm("var108", "undefined"),
    /* 109 */ Parm("var109", "undefined"),
    /* 110 */ Parm("var110", "undefined"),
    /* 111 */ Parm("var111", "undefined"),
    /* 112 */ Parm("var112", "undefined"),
    /* 113 */ Parm("var113", "undefined"),
    /* 114 */ Parm("var114", "undefined"),
    /* 115 */ Parm("var115", "undefined"),
    /* 116 */ Parm("var116", "undefined"),
    /* 117 */ Parm("var117", "undefined"),
    /* 118 */ Parm("var118", "undefined"),
    /* 119 */ Parm("var119", "undefined"),
    /* 120 */ Parm("var120", "undefined"),
    /* 121 */ Parm("NO2", "Nitrogen dioxide [kg kg**-1]"),
    /* 122 */ Parm("SO2", "Sulphur dioxide [kg kg**-1]"),
    /* 123 */ Parm("CO", "Carbon monoxide [kg kg**-1]"),
    /* 124 */ Parm("HCHO", "Formaldehyde [kg kg**-1]"),
    /* 125 */ Parm("TCNO2", "Total column Nitrogen dioxide [kg m**-2]"),
    /* 126 */ Parm("TCSO2", "Total column Sulphur dioxide [kg m**-2]"),
    /* 127 */ Parm("TCCO", "Total column Carbon monoxide [kg m**-2]"),
    /* 128 */ Parm("TCHCHO", "Total column Formaldehyde [kg m**-2]"),
    /* 129 */ Parm("NOX", "Nitrogen Oxides [kg kg**-1]"),
    /* 130 */ Parm("TCNOX", "Total Column Nitrogen Oxides [kg m**-2]"),
    /* 131 */ Parm("GRG1", "Reactive tracer 1 mass mixing ratio [kg kg**-1]"),
    /* 132 */ Parm("TCGRG1", "Total column GRG tracer 1 [kg m**-2]"),
    /* 133 */ Parm("GRG2", "Reactive tracer 2 mass mixing ratio [kg kg**-1]"),
    /* 134 */ Parm("TCGRG2", "Total column GRG tracer 2 [kg m**-2]"),
    /* 135 */ Parm("GRG3", "Reactive tracer 3 mass mixing ratio [kg kg**-1]"),
    /* 136 */ Parm("TCGRG3", "Total column GRG tracer 3 [kg m**-2]"),
    /* 137 */ Parm("GRG4", "Reactive tracer 4 mass mixing ratio [kg kg**-1]"),
    /* 138 */ Parm("TCGRG4", "Total column GRG tracer 4 [kg m**-2]"),
    /* 139 */ Parm("GRG5", "Reactive tracer 5 mass mixing ratio [kg kg**-1]"),
    /* 140 */ Parm("TCGRG5", "Total column GRG tracer 5 [kg m**-2]"),
    /* 141 */ Parm("GRG6", "Reactive tracer 6 mass mixing ratio [kg kg**-1]"),
    /* 142 */ Parm("TCGRG6", "Total column GRG tracer 6 [kg m**-2]"),
    /* 143 */ Parm("GRG7", "Reactive tracer 7 mass mixing ratio [kg kg**-1]"),
    /* 144 */ Parm("TCGRG7", "Total column GRG tracer 7 [kg m**-2]"),
    /* 145 */ Parm("GRG8", "Reactive tracer 8 mass mixing ratio [kg kg**-1]"),
    /* 146 */ Parm("TCGRG8", "Total column GRG tracer 8 [kg m**-2]"),
    /* 147 */ Parm("GRG9", "Reactive tracer 9 mass mixing ratio [kg kg**-1]"),
    /* 148 */ Parm("TCGRG9", "Total column GRG tracer 9 [kg m**-2]"),
    /* 149 */ Parm("GRG10", "Reactive tracer 10 mass mixing ratio [kg kg**-1]"),
    /* 150 */ Parm("TCGRG10", "Total column GRG tracer 10 [kg m**-2]"),
    /* 151 */ Parm("SFNOX", "Surface flux Nitrogen oxides [kg m**-2 s**-1]"),
    /* 152 */ Parm("SFNO2", "Surface flux Nitrogen dioxide [kg m**-2 s**-1]"),
    /* 153 */ Parm("SFSO2", "Surface flux Sulphur dioxide [kg m**-2 s**-1]"),
    /* 154 */ Parm("SFCO2", "Surface flux Carbon monoxide [kg m**-2 s**-1]"),
    /* 155 */ Parm("SFHCHO", "Surface flux Formaldehyde [kg m**-2 s**-1]"),
    /* 156 */ Parm("SFGO3", "Surface flux GEMS Ozone [kg m**-2 s**-1]"),
    /* 157 */ Parm("SFGR1", "Surface flux reactive tracer 1 [kg m**-2 s**-1]"),
    /* 158 */ Parm("SFGR2", "Surface flux reactive tracer 2 [kg m**-2 s**-1]"),
    /* 159 */ Parm("SFGR3", "Surface flux reactive tracer 3 [kg m**-2 s**-1]"),
    /* 160 */ Parm("SFGR4", "Surface flux reactive tracer 4 [kg m**-2 s**-1]"),
    /* 161 */ Parm("SFGR5", "Surface flux reactive tracer 5 [kg m**-2 s**-1]"),
    /* 162 */ Parm("SFGR6", "Surface flux reactive tracer 6 [kg m**-2 s**-1]"),
    /* 163 */ Parm("SFGR7", "Surface flux reactive tracer 7 [kg m**-2 s**-1]"),
    /* 164 */ Parm("SFGR8", "Surface flux reactive tracer 8 [kg m**-2 s**-1]"),
    /* 165 */ Parm("SFGR9", "Surface flux reactive tracer 9 [kg m**-2 s**-1]"),
    /* 166 */ Parm("SFGR10", "Surface flux reactive tracer 10 [kg m**-2 s**-1]"),
    /* 167 */ Parm("var167", "undefined"),
    /* 168 */ Parm("var168", "undefined"),
    /* 169 */ Parm("var169", "undefined"),
    /* 170 */ Parm("var170", "undefined"),
    /* 171 */ Parm("var171", "undefined"),
    /* 172 */ Parm("var172", "undefined"),
    /* 173 */ Parm("var173", "undefined"),
    /* 174 */ Parm("var174", "undefined"),
    /* 175 */ Parm("var175", "undefined"),
    /* 176 */ Parm("var176", "undefined"),
    /* 177 */ Parm("var177", "undefined"),
    /* 178 */ Parm("var178", "undefined"),
    /* 179 */ Parm("var179", "undefined"),
    /* 180 */ Parm("var180", "undefined"),
    /* 181 */ Parm("Ra", "Radon [kg kg**-1]"),
    /* 182 */ Parm("SF6", "Sulphur Hexafluoride [kg kg**-1]"),
    /* 183 */ Parm("TCRa", "Total column Radon [kg m**-2]"),
    /* 184 */ Parm("TCSF6", "Total column Sulphur Hexafluoride [kg m**-2]"),
    /* 185 */
    Parm(
        "SF6APF",
        "Anthropogenic Emissions of Sulphur Hexafluoride [kg m**-2 s**-1]",
    ),
    /* 186 */ Parm("var186", "undefined"),
    /* 187 */ Parm("var187", "undefined"),
    /* 188 */ Parm("var188", "undefined"),
    /* 189 */ Parm("var189", "undefined"),
    /* 190 */ Parm("var190", "undefined"),
    /* 191 */ Parm("var191", "undefined"),
    /* 192 */ Parm("var192", "undefined"),
    /* 193 */ Parm("var193", "undefined"),
    /* 194 */ Parm("var194", "undefined"),
    /* 195 */ Parm("var195", "undefined"),
    /* 196 */ Parm("var196", "undefined"),
    /* 197 */ Parm("var197", "undefined"),
    /* 198 */ Parm("var198", "undefined"),
    /* 199 */ Parm("var199", "undefined"),
    /* 200 */ Parm("var200", "undefined"),
    /* 201 */ Parm("var201", "undefined"),
    /* 202 */ Parm("var202", "undefined"),
    /* 203 */ Parm("GO3", "GEMS Ozone [kg kg**-1]"),
    /* 204 */ Parm("var204", "undefined"),
    /* 205 */ Parm("var205", "undefined"),
    /* 206 */ Parm("GTCO3", "GEMS Total column ozone [kg m**-2]"),
    /* 207 */ Parm("AOD550", "Total Aerosol Optical Depth at 550nm [-]"),
    /* 208 */ Parm("SSAOD550", "Sea Salt Aerosol Optical Depth at 550nm [-]"),
    /* 209 */ Parm("DUAOD550", "Dust Aerosol Optical Depth at 550nm [-]"),
    /* 210 */
    Parm(
        "OMAOD550",
        "Organic Matter Aerosol Optical Depth at 550nm [-]",
    ),
    /* 211 */
    Parm(
        "BCAOD550",
        "Black Carbon Aerosol Optical Depth at 550nm [-]",
    ),
    /* 212 */ Parm("SUAOD550", "Sulphate Aerosol Optical Depth at 550nm [-]"),
    /* 213 */ Parm("AOD469", "Total Aerosol Optical Depth at 469nm [-]"),
    /* 214 */ Parm("AOD670", "Total Aerosol Optical Depth at 670nm [-]"),
    /* 215 */ Parm("AOD865", "Total Aerosol Optical Depth at 865nm [-]"),
    /* 216 */ Parm("AOD1240", "Total Aerosol Optical Depth at 1240nm [-]"),
    /* 217 */ Parm("var217", "undefined"),
    /* 218 */ Parm("var218", "undefined"),
    /* 219 */ Parm("var219", "undefined"),
    /* 220 */ Parm("var220", "undefined"),
    /* 221 */ Parm("var221", "undefined"),
    /* 222 */ Parm("var222", "undefined"),
    /* 223 */ Parm("var223", "undefined"),
    /* 224 */ Parm("var224", "undefined"),
    /* 225 */ Parm("var225", "undefined"),
    /* 226 */ Parm("var226", "undefined"),
    /* 227 */ Parm("var227", "undefined"),
    /* 228 */ Parm("var228", "undefined"),
    /* 229 */ Parm("var229", "undefined"),
    /* 230 */ Parm("var230", "undefined"),
    /* 231 */ Parm("var231", "undefined"),
    /* 232 */ Parm("var232", "undefined"),
    /* 233 */ Parm("var233", "undefined"),
    /* 234 */ Parm("var234", "undefined"),
    /* 235 */ Parm("var235", "undefined"),
    /* 236 */ Parm("var236", "undefined"),
    /* 237 */ Parm("var237", "undefined"),
    /* 238 */ Parm("var238", "undefined"),
    /* 239 */ Parm("var239", "undefined"),
    /* 240 */ Parm("var240", "undefined"),
    /* 241 */ Parm("var241", "undefined"),
    /* 242 */ Parm("var242", "undefined"),
    /* 243 */ Parm("var243", "undefined"),
    /* 244 */ Parm("var244", "undefined"),
    /* 245 */ Parm("var245", "undefined"),
    /* 246 */ Parm("var246", "undefined"),
    /* 247 */ Parm("var247", "undefined"),
    /* 248 */ Parm("var248", "undefined"),
    /* 249 */ Parm("var249", "undefined"),
    /* 250 */ Parm("var250", "undefined"),
    /* 251 */ Parm("var251", "undefined"),
    /* 252 */ Parm("var252", "undefined"),
    /* 253 */ Parm("var253", "undefined"),
    /* 254 */ Parm("var254", "undefined"),
    /* 255 */ Parm("var255", "undefined"),
];
