use super::Parm;

pub const NCEP_TABLE_MDL_PARM_TABLE: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */ Parm("PRES", "Pressure [Pa]"),
    /* 2 */ Parm("PRMSL", "Pressure reduced to MSL [Pa]"),
    /* 3 */ Parm("PTEND", "Pressure tendency [Pa/s]"),
    /* 4 */ Parm("PVORT", "Pot. vorticity [km^2/kg/s]"),
    /* 5 */ Parm("ICAHT", "ICAO Standard Atmosphere Reference Height [M]"),
    /* 6 */ Parm("GP", "Geopotential [m^2/s^2]"),
    /* 7 */ Parm("HGT", "Geopotential height [gpm]"),
    /* 8 */ Parm("DIST", "Geometric height [m]"),
    /* 9 */ Parm("HSTDV", "Std dev of height [m]"),
    /* 10 */ Parm("TOZNE", "Total ozone [Dobson]"),
    /* 11 */ Parm("TMP", "Temp. [K]"),
    /* 12 */ Parm("VTMP", "Virtual temp. [K]"),
    /* 13 */ Parm("POT", "Potential temp. [K]"),
    /* 14 */ Parm("EPOT", "Pseudo-adiabatic pot. temp. [K]"),
    /* 15 */ Parm("TMAX", "Max. temp. [K]"),
    /* 16 */ Parm("TMIN", "Min. temp. [K]"),
    /* 17 */ Parm("DPT", "Dew point temp. [K]"),
    /* 18 */ Parm("DEPR", "Dew point depression [K]"),
    /* 19 */ Parm("LAPR", "Lapse rate [K/m]"),
    /* 20 */ Parm("VIS", "Visibility [m]"),
    /* 21 */ Parm("RDSP1", "Radar spectra (1) [non-dim]"),
    /* 22 */ Parm("RDSP2", "Radar spectra (2) [non-dim]"),
    /* 23 */ Parm("RDSP3", "Radar spectra (3) [non-dim]"),
    /* 24 */ Parm("PLI", "Parcel lifted index (to 500 hPa) [K]"),
    /* 25 */ Parm("TMPA", "Temp. anomaly [K]"),
    /* 26 */ Parm("PRESA", "Pressure anomaly [Pa]"),
    /* 27 */ Parm("GPA", "Geopotential height anomaly [gpm]"),
    /* 28 */ Parm("WVSP1", "Wave spectra (1) [non-dim]"),
    /* 29 */ Parm("WVSP2", "Wave spectra (2) [non-dim]"),
    /* 30 */ Parm("WVSP3", "Wave spectra (3) [non-dim]"),
    /* 31 */ Parm("WDIR", "Wind direction [deg]"),
    /* 32 */ Parm("WIND", "Wind speed [m/s]"),
    /* 33 */ Parm("UGRD", "u wind [m/s]"),
    /* 34 */ Parm("VGRD", "v wind [m/s]"),
    /* 35 */ Parm("STRM", "Stream function [m^2/s]"),
    /* 36 */ Parm("VPOT", "Velocity potential [m^2/s]"),
    /* 37 */ Parm("MNTSF", "Montgomery stream function [m^2/s^2]"),
    /* 38 */ Parm("SGCVV", "Sigma coord. vertical velocity [/s]"),
    /* 39 */ Parm("VVEL", "Pressure vertical velocity [Pa/s]"),
    /* 40 */ Parm("DZDT", "Geometric vertical velocity [m/s]"),
    /* 41 */ Parm("ABSV", "Absolute vorticity [/s]"),
    /* 42 */ Parm("ABSD", "Absolute divergence [/s]"),
    /* 43 */ Parm("RELV", "Relative vorticity [/s]"),
    /* 44 */ Parm("RELD", "Relative divergence [/s]"),
    /* 45 */ Parm("VUCSH", "Vertical u shear [/s]"),
    /* 46 */ Parm("VVCSH", "Vertical v shear [/s]"),
    /* 47 */ Parm("DIRC", "Direction of current [deg]"),
    /* 48 */ Parm("SPC", "Speed of current [m/s]"),
    /* 49 */ Parm("UOGRD", "u of current [m/s]"),
    /* 50 */ Parm("VOGRD", "v of current [m/s]"),
    /* 51 */ Parm("SPFH", "Specific humidity [kg/kg]"),
    /* 52 */ Parm("RH", "Relative humidity [%]"),
    /* 53 */ Parm("MIXR", "Humidity mixing ratio [kg/kg]"),
    /* 54 */ Parm("PWAT", "Precipitable water [kg/m^2]"),
    /* 55 */ Parm("VAPP", "Vapor pressure [Pa]"),
    /* 56 */ Parm("SATD", "Saturation deficit [Pa]"),
    /* 57 */ Parm("EVP", "Evaporation [kg/m^2]"),
    /* 58 */ Parm("CICE", "Cloud Ice [kg/m^2]"),
    /* 59 */ Parm("PRATE", "Precipitation rate [kg/m^2/s]"),
    /* 60 */ Parm("TSTM", "Thunderstorm probability [%]"),
    /* 61 */ Parm("APCP", "Total precipitation [kg/m^2]"),
    /* 62 */ Parm("NCPCP", "Large scale precipitation [kg/m^2]"),
    /* 63 */ Parm("ACPCP", "Convective precipitation [kg/m^2]"),
    /* 64 */ Parm("SRWEQ", "Snowfall rate water equiv. [kg/m^2/s]"),
    /* 65 */ Parm("WEASD", "Accum. snow [kg/m^2]"),
    /* 66 */ Parm("SNOD", "Snow depth [m]"),
    /* 67 */ Parm("MIXHT", "Mixed layer depth [m]"),
    /* 68 */ Parm("TTHDP", "Transient thermocline depth [m]"),
    /* 69 */ Parm("MTHD", "Main thermocline depth [m]"),
    /* 70 */ Parm("MTHA", "Main thermocline anomaly [m]"),
    /* 71 */ Parm("TCDC", "Total cloud cover [%]"),
    /* 72 */ Parm("CDCON", "Convective cloud cover [%]"),
    /* 73 */ Parm("LCDC", "Low level cloud cover [%]"),
    /* 74 */ Parm("MCDC", "Mid level cloud cover [%]"),
    /* 75 */ Parm("HCDC", "High level cloud cover [%]"),
    /* 76 */ Parm("CWAT", "Cloud water [kg/m^2]"),
    /* 77 */ Parm("BLI", "Best lifted index (to 500 hPa) [K]"),
    /* 78 */ Parm("SNOC", "Convective snow [kg/m^2]"),
    /* 79 */ Parm("SNOL", "Large scale snow [kg/m^2]"),
    /* 80 */ Parm("WTMP", "Water temp. [K]"),
    /* 81 */ Parm("LAND", "Land cover (land=1;sea=0) [fraction]"),
    /* 82 */ Parm("DSLM", "Deviation of sea level from mean [m]"),
    /* 83 */ Parm("SFCR", "Surface roughness [m]"),
    /* 84 */ Parm("ALBDO", "Albedo [%]"),
    /* 85 */ Parm("TSOIL", "Soil temp. [K]"),
    /* 86 */ Parm("SOILM", "Soil moisture content [kg/m^2]"),
    /* 87 */ Parm("VEG", "Vegetation [%]"),
    /* 88 */ Parm("SALTY", "Salinity [kg/kg]"),
    /* 89 */ Parm("DEN", "Density [kg/m^3]"),
    /* 90 */ Parm("WATR", "Water runoff [kg/m^2]"),
    /* 91 */ Parm("ICEC", "Ice concentration (ice=1;no ice=0) [fraction]"),
    /* 92 */ Parm("ICETK", "Ice thickness [m]"),
    /* 93 */ Parm("DICED", "Direction of ice drift [deg]"),
    /* 94 */ Parm("SICED", "Speed of ice drift [m/s]"),
    /* 95 */ Parm("UICE", "u of ice drift [m/s]"),
    /* 96 */ Parm("VICE", "v of ice drift [m/s]"),
    /* 97 */ Parm("ICEG", "Ice growth rate [m/s]"),
    /* 98 */ Parm("ICED", "Ice divergence [/s]"),
    /* 99 */ Parm("SNOM", "Snow melt [kg/m^2]"),
    /* 100 */ Parm("HTSGW", "Sig height of wind waves and swell [m]"),
    /* 101 */ Parm("WVDIR", "Direction of wind waves [deg]"),
    /* 102 */ Parm("WVHGT", "Sig height of wind waves [m]"),
    /* 103 */ Parm("WVPER", "Mean period of wind waves [s]"),
    /* 104 */ Parm("SWDIR", "Direction of swell waves [deg]"),
    /* 105 */ Parm("SWELL", "Sig height of swell waves [m]"),
    /* 106 */ Parm("SWPER", "Mean period of swell waves [s]"),
    /* 107 */ Parm("DIRPW", "Primary wave direction [deg]"),
    /* 108 */ Parm("PERPW", "Primary wave mean period [s]"),
    /* 109 */ Parm("DIRSW", "Secondary wave direction [deg]"),
    /* 110 */ Parm("PERSW", "Secondary wave mean period [s]"),
    /* 111 */ Parm("NSWRS", "Net short wave (surface) [W/m^2]"),
    /* 112 */ Parm("NLWRS", "Net long wave (surface) [W/m^2]"),
    /* 113 */ Parm("NSWRT", "Net short wave (top) [W/m^2]"),
    /* 114 */ Parm("NLWRT", "Net long wave (top) [W/m^2]"),
    /* 115 */ Parm("LWAVR", "Long wave [W/m^2]"),
    /* 116 */ Parm("SWAVR", "Short wave [W/m^2]"),
    /* 117 */ Parm("GRAD", "Global radiation [W/m^2]"),
    /* 118 */ Parm("BRTMP", "Brightness temperature [K]"),
    /* 119 */ Parm("LWRAD", "Radiance with respect to wave no. [W/m/sr]"),
    /* 120 */ Parm("SWRAD", "Radiance with respect ot wave len. [W/m^3/sr]"),
    /* 121 */ Parm("LHTFL", "Latent heat flux [W/m^2]"),
    /* 122 */ Parm("SHTFL", "Sensible heat flux [W/m^2]"),
    /* 123 */ Parm("BLYDP", "Boundary layer dissipation [W/m^2]"),
    /* 124 */ Parm("UFLX", "Zonal momentum flux [N/m^2]"),
    /* 125 */ Parm("VFLX", "Meridional momentum flux [N/m^2]"),
    /* 126 */ Parm("WMIXE", "Wind mixing energy [J]"),
    /* 127 */ Parm("IMGD", "Image data []"),
    /* 128 */ Parm("TMPF", "TEMPERATURE (Fahrenheit) [F]"),
    /* 129 */ Parm("MAXK", "DAYTIME MAX TEMP (MAX) (Kelvin) [K]"),
    /* 130 */ Parm("MAXF", "DAYTIME MAX TEMP (MAX) (deg F) [F]"),
    /* 131 */ Parm("NMAXK", "NORMAL MAX TEMPERATURE (Kelvin) [K]"),
    /* 132 */ Parm("NMAXF", "NORMAL MAX TEMPERATURE (deg F) [F]"),
    /* 133 */ Parm("DMAXK", "DEPARTURE FROM NORMAL MAX (K) [K]"),
    /* 134 */ Parm("DMAXF", "DEPARTURE FROM NORMAL MAX (deg F) [F]"),
    /* 135 */ Parm("MINK", "NIGHTTIME MIN TEMP (MIN) (Kelvin) [K]"),
    /* 136 */ Parm("MINF", "NIGHTTIME MIN TEMP (MIN) (deg F) [F]"),
    /* 137 */ Parm("NMINK", "NORMAL MIN TEMPERATURE (Kelvin) [K]"),
    /* 138 */ Parm("NMINF", "NORMAL NIGHTTIME MIN TEMP (deg F) [F]"),
    /* 139 */ Parm("DMINK", "DEPARTURE FROM NORMAL MIN (K) [K]"),
    /* 140 */ Parm("DMINF", "DEPARTURE FROM NORMAL MIN (deg F) [F]"),
    /* 141 */ Parm("DWPF", "DEW POINT TEMPERATURE (deg F) [F]"),
    /* 142 */ Parm("DPDF", "DEW POINT DEPRESSION (deg F) [F]"),
    /* 143 */ Parm("HTINF", "HEAT INDEX (deg F) [F]"),
    /* 144 */ Parm("WNCHF", "WIND CHILL (deg F) [F]"),
    /* 145 */ Parm("var145", "undefined"),
    /* 146 */ Parm("POP", "PROB OF 0.01 IN. OF PRECIP (PoP) [%]"),
    /* 147 */ Parm("PQPF2", "PROB OF QPF >= 0.10 INCHES [%]"),
    /* 148 */ Parm("PQPF3", "PROB OF QPF >= 0.25 INCHES [%]"),
    /* 149 */ Parm("PQPF4", "PROB OF QPF >= 0.50 INCHES [%]"),
    /* 150 */ Parm("PQPF5", "PROB OF QPF >= 1.00 INCHES [%]"),
    /* 151 */ Parm("PQPF6", "PROB OF QPF >= 2.00 INCHES [%]"),
    /* 152 */ Parm("PQPF7", "PROB OF QPF >= 3.00 INCHES FUTURE [%]"),
    /* 153 */ Parm("BQPF", "BEST CATEGORY OF QPF [num]"),
    /* 154 */ Parm("NPOP", "NML REL. FREQ. OF 0.01 IN OF PCP [%]"),
    /* 155 */ Parm("DPOP", "DEPARTURE FROM NML OF 0.01 POP [%]"),
    /* 156 */ Parm("PCPM", "EXPECTED VALUE OF PRECIPITATION [mm]"),
    /* 157 */ Parm("PCPI", "EXPECTED VALUE OF PRECIPITATION [in]"),
    /* 158 */ Parm("CPCPM", "CONDITIONAL EXPECTED PRECIP AMT [mm]"),
    /* 159 */ Parm("CPCPI", "CONDITIONAL EXPECTED PRECIP AMT [in]"),
    /* 160 */ Parm("PSNA1", "PROB OF SNOW AMOUNT >= 0.10 [%]"),
    /* 161 */ Parm("PSNA2", "PROB OF SNOW AMOUNT >= 2 INCHES [%]"),
    /* 162 */ Parm("PSNA3", "PROB OF SNOW AMOUNT >= 4 INCHES [%]"),
    /* 163 */ Parm("PSNA4", "PROB OF SNOW AMOUNT >= 6 INCHES [%]"),
    /* 164 */ Parm("PSNA5", "PROB OF SNOW AMOUNT >= 8 INCHES [%]"),
    /* 165 */ Parm("BSNA", "BEST CATEGORY FOR SNOW AMOUNT [num]"),
    /* 166 */ Parm("SNWM", "EXPECTED VALUE OF SNOW AMOUNT [mm]"),
    /* 167 */ Parm("SNWI", "EXPECTED VALUE OF SNOW AMOUNT [in]"),
    /* 168 */ Parm("MWSPK", "INFLATED MAX WIND SPEED (knots) [kts]"),
    /* 169 */ Parm("IWSPM", "INFLATED WIND SPEED (meter/sec) [m/s]"),
    /* 170 */ Parm("SKNT", "INFLATED WIND SPEED (knots) [kts]"),
    /* 171 */ Parm("PWSP1", "PROB OF MAX WIND SPEED 0-12 kts [%]"),
    /* 172 */ Parm("PWSP2", "PROB OF MAX WIND SPEED 13-21 kts [%]"),
    /* 173 */ Parm("PWSP3", "PROB OF MAX WIND SPEED 22-31 kts [%]"),
    /* 174 */ Parm("PWSP4", "PROB OF MAX WIND SPEED >=32 kts [%]"),
    /* 175 */ Parm("WSPDC", "CATEGORICAL MAX WIND SPEED [num]"),
    /* 176 */ Parm("XSPDM", "EXPECTED VALUE OF MAX WIND SPEED [m/s]"),
    /* 177 */ Parm("XSPDK", "EXPECTED VALUE OF MAX WIND SPEED [kts]"),
    /* 178 */ Parm("PWDRN", "PROB OF WIND DIRECTION NORTH [%]"),
    /* 179 */ Parm("PWDRNE", "PROB OF WIND DIRECTION NORTHEAST [%]"),
    /* 180 */ Parm("PWDRE", "PROB OF WIND DIRECTION EAST [%]"),
    /* 181 */ Parm("PWDRSE", "PROB OF WIND DIRECTION SOUTHEAST [%]"),
    /* 182 */ Parm("PWDRS", "PROB OF WIND DIRECTION SOUTH [%]"),
    /* 183 */ Parm("PWDRSW", "PROB OF WIND DIRECTION SOUTHWEST [%]"),
    /* 184 */ Parm("PWDRW", "PROB OF WIND DIRECTION WEST [%]"),
    /* 185 */ Parm("PWDRNW", "PROB OF WIND DIRECTION NORTHWEST [%]"),
    /* 186 */ Parm("WDIRC", "CATEGORICAL WIND DIRECTION [num]"),
    /* 187 */ Parm("var187", "undefined"),
    /* 188 */ Parm("PSKCL", "PROB OF TOTAL SKY"),
    /* 189 */ Parm("PSKFW", "PROB OF TOTAL SKY"),
    /* 190 */ Parm("PSKSC", "PROB OF TOTAL SKY"),
    /* 191 */ Parm("PSKBK", "PROB OF TOTAL SKY"),
    /* 192 */ Parm("PSKOV", "PROB OF TOTAL SKY"),
    /* 193 */ Parm("SKYC", "CATEGORICAL TOTAL SKY COVER [num]"),
    /* 194 */ Parm("MSKCL", "PROB MEAN SKY CVR"),
    /* 195 */ Parm("MSKOV", "PROB MEAN SKY CVR"),
    /* 196 */ Parm("MSKMC", "PROB MEAN SKY CVR"),
    /* 197 */ Parm("MSKPC", "PROB MEAN SKY CVR"),
    /* 198 */ Parm("MSKMO", "PROB MEAN SKY CVR"),
    /* 199 */ Parm("MSKYC", "CATEGORICAL MEAN SKY COVER [num]"),
    /* 200 */ Parm("PCIG1", "PROB OF CIG HGT < 200 FT [%]"),
    /* 201 */ Parm("PCIG2", "PROB OF CIG HGT 200-400 FT [%]"),
    /* 202 */ Parm("PCIG3", "PROB OF CIG HGT 500-900 FT [%]"),
    /* 203 */ Parm("PCIG4", "PROB OF CIG HGT 1000-3000 FT [%]"),
    /* 204 */ Parm("PCIG5", "PROB OF CIG HGT 3100-6500 FT [%]"),
    /* 205 */ Parm("PCIG6", "PROB OF CIG HGT 6600-12000 FT [%]"),
    /* 206 */ Parm("PCIG7", "PROB OF CIG HGT > 12000 FT [%]"),
    /* 207 */ Parm("BCIG", "BEST CATEGORY OF CEILING HEIGHT [num]"),
    /* 208 */ Parm("PVIS1", "PROB OF VIS <=1/4 MILE [%]"),
    /* 209 */ Parm("PVIS2", "PROB OF VIS <=1/2 MILE [%]"),
    /* 210 */ Parm("PVIS3", "PROB OF VIS <=7/8 MILE [%]"),
    /* 211 */ Parm("PVIS4", "PROB OF VIS <=2 3/4 MILES [%]"),
    /* 212 */ Parm("PVIS5", "PROB OF VIS <=5 MILES [%]"),
    /* 213 */ Parm("PVIS6", "PROB OF VIS <=6 MILES [%]"),
    /* 214 */ Parm("VISC", "CATEGORICAL VISIBILITY [num]"),
    /* 215 */ Parm("POBVN", "PROB OF OBSTRUCTION TO VIS"),
    /* 216 */ Parm("POBVH", "PROB OF OBSTRUCTION TO VIS"),
    /* 217 */ Parm("POBVM", "PROB OF OBSTRUCTION TO VIS"),
    /* 218 */ Parm("POBVF", "PROB OF OBSTRUCTION TO VIS"),
    /* 219 */ Parm("POVBL", "PROB OF BLOWING OBVIS [%]"),
    /* 220 */ Parm("OBVC", "BEST CATEGORY OF OBVIS [num]"),
    /* 221 */ Parm("var221", "undefined"),
    /* 222 */ Parm("NTSM", "NORMAL PROB OF THUNDERSTORMS [%]"),
    /* 223 */ Parm("CSVR", "COND PROB OF SEVERE WEATHER [%]"),
    /* 224 */ Parm("USVR", "UNCOND PROB OF SEVERE WX [%]"),
    /* 225 */ Parm("NSVR", "NORMAL PROB OF SEVERE WX [%]"),
    /* 226 */ Parm("UHAI", "UNCONDITIONAL PROB OF HAIL [%]"),
    /* 227 */ Parm("UTOR", "UNCONDITIONAL PROB OF TORNADO [%]"),
    /* 228 */ Parm("UTSW", "UNCOND PROB OF DAMAGING WIND [%]"),
    /* 229 */ Parm("CFZI", "COND PROB FRZING PRECIP (INSTANT) [%]"),
    /* 230 */ Parm("UFZI", "UNCND PROB FRZING PRECIP (INSTNT) [%]"),
    /* 231 */ Parm("CZNI", "COND PROB FROZEN PRECIP (INSTANT) [%]"),
    /* 232 */ Parm("UZNI", "UNCND PROB FROZEN PRECIP (INSTNT) [%]"),
    /* 233 */ Parm("CLQI", "COND PROB LIQUID PRECIP (INSTANT) [%]"),
    /* 234 */ Parm("ULQI", "UNCND PROB LIQUID PRECIP (INSTNT) [%]"),
    /* 235 */ Parm("PTYPI", "CATEGORICAL PRECIP TYPE (INSTANT) [num]"),
    /* 236 */ Parm("CPOZP", "COND PROB OF FRZING PRECIP [%]"),
    /* 237 */ Parm("UPOZP", "UNCOND PROB OF FRZING PRECIP [%]"),
    /* 238 */ Parm("CPOS", "COND PROB OF SNOW (CPoS) [%]"),
    /* 239 */ Parm("UPOS", "UNCOND PROB OF SNOW (CPoS) [%]"),
    /* 240 */ Parm("CPORS", "COND PROB OF RAIN/SNOW MIXED [%]"),
    /* 241 */ Parm("UPORS", "UNCOND PROB OF RAIN/SNOW MIXED [%]"),
    /* 242 */ Parm("CPORA", "COND PROB OF RAIN [%]"),
    /* 243 */ Parm("var243", "undefined"),
    /* 244 */ Parm("BPCPT", "BEST CATEGORY OF PRECIP TYPE [num]"),
    /* 245 */ Parm("POPOH", "POPO PRECIP OCCURRING AT AN HOUR [%]"),
    /* 246 */ Parm("POPOP", "POPO PRECIP DURING A PERIOD [%]"),
    /* 247 */ Parm("CPDRZ", "COND PROB OF DRIZZLE [%]"),
    /* 248 */ Parm("CPSTY", "COND PROB OF CONT (STEADY) PRECIP [%]"),
    /* 249 */ Parm("CPSHW", "COND PROB OF SHOWERS [%]"),
    /* 250 */ Parm("BPCHR", "BEST CAT PRECIP CHARACTERISTIC [num]"),
    /* 251 */ Parm("SUNSH", "PERCENT OF POSSIBLE SUNSHINE [%]"),
    /* 252 */ Parm("HRSUN", "HOURS OF SUNSHINE [hrs]"),
    /* 253 */ Parm("SCQP", "SCAN 0-3H CATEGORICAL QPF [num]"),
    /* 254 */ Parm("SCTS", "SCAN 0-3H C-G LIGHTNING PROB [%]"),
    /* 255 */ Parm("var255", "undefined"),
];
