use super::Parm;

pub const NCEP_OPN_PARM_TABLE: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */ Parm("PRES", "Pressure [Pa]"),
    /* 2 */ Parm("PRMSL", "Pressure reduced to MSL [Pa]"),
    /* 3 */ Parm("PTEND", "Pressure tendency [Pa/s]"),
    /* 4 */ Parm("PVORT", "Pot. vorticity [km^2/kg/s]"),
    /* 5 */ Parm("ICAHT", "ICAO Standard Atmosphere Reference Height [M]"),
    /* 6 */ Parm("GP", "Geopotential [m^2/s^2]"),
    /* 7 */ Parm("HGT", "Geopotential height [gpm]"),
    /* 8 */ Parm("DIST", "Geometric height [m]"),
    /* 9 */ Parm("HSTDV", "Std dev of height [m]"),
    /* 10 */ Parm("TOZNE", "Total ozone [Dobson]"),
    /* 11 */ Parm("TMP", "Temp. [K]"),
    /* 12 */ Parm("VTMP", "Virtual temp. [K]"),
    /* 13 */ Parm("POT", "Potential temp. [K]"),
    /* 14 */ Parm("EPOT", "Pseudo-adiabatic pot. temp. [K]"),
    /* 15 */ Parm("TMAX", "Max. temp. [K]"),
    /* 16 */ Parm("TMIN", "Min. temp. [K]"),
    /* 17 */ Parm("DPT", "Dew point temp. [K]"),
    /* 18 */ Parm("DEPR", "Dew point depression [K]"),
    /* 19 */ Parm("LAPR", "Lapse rate [K/m]"),
    /* 20 */ Parm("VIS", "Visibility [m]"),
    /* 21 */ Parm("RDSP1", "Radar spectra (1) [non-dim]"),
    /* 22 */ Parm("RDSP2", "Radar spectra (2) [non-dim]"),
    /* 23 */ Parm("RDSP3", "Radar spectra (3) [non-dim]"),
    /* 24 */ Parm("PLI", "Parcel lifted index (to 500 hPa) [K]"),
    /* 25 */ Parm("TMPA", "Temp. anomaly [K]"),
    /* 26 */ Parm("PRESA", "Pressure anomaly [Pa]"),
    /* 27 */ Parm("GPA", "Geopotential height anomaly [gpm]"),
    /* 28 */ Parm("WVSP1", "Wave spectra (1) [non-dim]"),
    /* 29 */ Parm("WVSP2", "Wave spectra (2) [non-dim]"),
    /* 30 */ Parm("WVSP3", "Wave spectra (3) [non-dim]"),
    /* 31 */ Parm("WDIR", "Wind direction [deg]"),
    /* 32 */ Parm("WIND", "Wind speed [m/s]"),
    /* 33 */ Parm("UGRD", "u wind [m/s]"),
    /* 34 */ Parm("VGRD", "v wind [m/s]"),
    /* 35 */ Parm("STRM", "Stream function [m^2/s]"),
    /* 36 */ Parm("VPOT", "Velocity potential [m^2/s]"),
    /* 37 */ Parm("MNTSF", "Montgomery stream function [m^2/s^2]"),
    /* 38 */ Parm("SGCVV", "Sigma coord. vertical velocity [/s]"),
    /* 39 */ Parm("VVEL", "Pressure vertical velocity [Pa/s]"),
    /* 40 */ Parm("DZDT", "Geometric vertical velocity [m/s]"),
    /* 41 */ Parm("ABSV", "Absolute vorticity [/s]"),
    /* 42 */ Parm("ABSD", "Absolute divergence [/s]"),
    /* 43 */ Parm("RELV", "Relative vorticity [/s]"),
    /* 44 */ Parm("RELD", "Relative divergence [/s]"),
    /* 45 */ Parm("VUCSH", "Vertical u shear [/s]"),
    /* 46 */ Parm("VVCSH", "Vertical v shear [/s]"),
    /* 47 */ Parm("DIRC", "Direction of current [deg]"),
    /* 48 */ Parm("SPC", "Speed of current [m/s]"),
    /* 49 */ Parm("UOGRD", "u of current [m/s]"),
    /* 50 */ Parm("VOGRD", "v of current [m/s]"),
    /* 51 */ Parm("SPFH", "Specific humidity [kg/kg]"),
    /* 52 */ Parm("RH", "Relative humidity [%]"),
    /* 53 */ Parm("MIXR", "Humidity mixing ratio [kg/kg]"),
    /* 54 */ Parm("PWAT", "Precipitable water [kg/m^2]"),
    /* 55 */ Parm("VAPP", "Vapor pressure [Pa]"),
    /* 56 */ Parm("SATD", "Saturation deficit [Pa]"),
    /* 57 */ Parm("EVP", "Evaporation [kg/m^2]"),
    /* 58 */ Parm("CICE", "Cloud Ice [kg/m^2]"),
    /* 59 */ Parm("PRATE", "Precipitation rate [kg/m^2/s]"),
    /* 60 */ Parm("TSTM", "Thunderstorm probability [%]"),
    /* 61 */ Parm("APCP", "Total precipitation [kg/m^2]"),
    /* 62 */ Parm("NCPCP", "Large scale precipitation [kg/m^2]"),
    /* 63 */ Parm("ACPCP", "Convective precipitation [kg/m^2]"),
    /* 64 */ Parm("SRWEQ", "Snowfall rate water equiv. [kg/m^2/s]"),
    /* 65 */ Parm("WEASD", "Accum. snow [kg/m^2]"),
    /* 66 */ Parm("SNOD", "Snow depth [m]"),
    /* 67 */ Parm("MIXHT", "Mixed layer depth [m]"),
    /* 68 */ Parm("TTHDP", "Transient thermocline depth [m]"),
    /* 69 */ Parm("MTHD", "Main thermocline depth [m]"),
    /* 70 */ Parm("MTHA", "Main thermocline anomaly [m]"),
    /* 71 */ Parm("TCDC", "Total cloud cover [%]"),
    /* 72 */ Parm("CDCON", "Convective cloud cover [%]"),
    /* 73 */ Parm("LCDC", "Low level cloud cover [%]"),
    /* 74 */ Parm("MCDC", "Mid level cloud cover [%]"),
    /* 75 */ Parm("HCDC", "High level cloud cover [%]"),
    /* 76 */ Parm("CWAT", "Cloud water [kg/m^2]"),
    /* 77 */ Parm("BLI", "Best lifted index (to 500 hPa) [K]"),
    /* 78 */ Parm("SNOC", "Convective snow [kg/m^2]"),
    /* 79 */ Parm("SNOL", "Large scale snow [kg/m^2]"),
    /* 80 */ Parm("WTMP", "Water temp. [K]"),
    /* 81 */ Parm("LAND", "Land cover (land=1;sea=0) [fraction]"),
    /* 82 */ Parm("DSLM", "Deviation of sea level from mean [m]"),
    /* 83 */ Parm("SFCR", "Surface roughness [m]"),
    /* 84 */ Parm("ALBDO", "Albedo [%]"),
    /* 85 */ Parm("TSOIL", "Soil temp. [K]"),
    /* 86 */ Parm("SOILM", "Soil moisture content [kg/m^2]"),
    /* 87 */ Parm("VEG", "Vegetation [%]"),
    /* 88 */ Parm("SALTY", "Salinity [kg/kg]"),
    /* 89 */ Parm("DEN", "Density [kg/m^3]"),
    /* 90 */ Parm("WATR", "Water runoff [kg/m^2]"),
    /* 91 */ Parm("ICEC", "Ice concentration (ice=1;no ice=0) [fraction]"),
    /* 92 */ Parm("ICETK", "Ice thickness [m]"),
    /* 93 */ Parm("DICED", "Direction of ice drift [deg]"),
    /* 94 */ Parm("SICED", "Speed of ice drift [m/s]"),
    /* 95 */ Parm("UICE", "u of ice drift [m/s]"),
    /* 96 */ Parm("VICE", "v of ice drift [m/s]"),
    /* 97 */ Parm("ICEG", "Ice growth rate [m/s]"),
    /* 98 */ Parm("ICED", "Ice divergence [/s]"),
    /* 99 */ Parm("SNOM", "Snow melt [kg/m^2]"),
    /* 100 */ Parm("HTSGW", "Sig height of wind waves and swell [m]"),
    /* 101 */ Parm("WVDIR", "Direction of wind waves [deg]"),
    /* 102 */ Parm("WVHGT", "Sig height of wind waves [m]"),
    /* 103 */ Parm("WVPER", "Mean period of wind waves [s]"),
    /* 104 */ Parm("SWDIR", "Direction of swell waves [deg]"),
    /* 105 */ Parm("SWELL", "Sig height of swell waves [m]"),
    /* 106 */ Parm("SWPER", "Mean period of swell waves [s]"),
    /* 107 */ Parm("DIRPW", "Primary wave direction [deg]"),
    /* 108 */ Parm("PERPW", "Primary wave mean period [s]"),
    /* 109 */ Parm("DIRSW", "Secondary wave direction [deg]"),
    /* 110 */ Parm("PERSW", "Secondary wave mean period [s]"),
    /* 111 */ Parm("NSWRS", "Net short wave (surface) [W/m^2]"),
    /* 112 */ Parm("NLWRS", "Net long wave (surface) [W/m^2]"),
    /* 113 */ Parm("NSWRT", "Net short wave (top) [W/m^2]"),
    /* 114 */ Parm("NLWRT", "Net long wave (top) [W/m^2]"),
    /* 115 */ Parm("LWAVR", "Long wave [W/m^2]"),
    /* 116 */ Parm("SWAVR", "Short wave [W/m^2]"),
    /* 117 */ Parm("GRAD", "Global radiation [W/m^2]"),
    /* 118 */ Parm("BRTMP", "Brightness temperature [K]"),
    /* 119 */ Parm("LWRAD", "Radiance with respect to wave no. [W/m/sr]"),
    /* 120 */ Parm("SWRAD", "Radiance with respect ot wave len. [W/m^3/sr]"),
    /* 121 */ Parm("LHTFL", "Latent heat flux [W/m^2]"),
    /* 122 */ Parm("SHTFL", "Sensible heat flux [W/m^2]"),
    /* 123 */ Parm("BLYDP", "Boundary layer dissipation [W/m^2]"),
    /* 124 */ Parm("UFLX", "Zonal momentum flux [N/m^2]"),
    /* 125 */ Parm("VFLX", "Meridional momentum flux [N/m^2]"),
    /* 126 */ Parm("WMIXE", "Wind mixing energy [J]"),
    /* 127 */ Parm("IMGD", "Image data []"),
    /* 128 */ Parm("MSLSA", "Mean sea level pressure (Std Atm) [Pa]"),
    /* 129 */ Parm("MSLMA", "Mean sea level pressure (MAPS) [Pa]"),
    /* 130 */ Parm("MSLET", "Mean sea level pressure (ETA model) [Pa]"),
    /* 131 */ Parm("LFTX", "Surface lifted index [K]"),
    /* 132 */ Parm("4LFTX", "Best (4-layer) lifted index [K]"),
    /* 133 */ Parm("KX", "K index [K]"),
    /* 134 */ Parm("SX", "Sweat index [K]"),
    /* 135 */ Parm("MCONV", "Horizontal moisture divergence [kg/kg/s]"),
    /* 136 */ Parm("VWSH", "Vertical speed shear [1/s]"),
    /* 137 */ Parm("TSLSA", "3-hr pressure tendency (Std Atmos Red) [Pa/s]"),
    /* 138 */ Parm("BVF2", "Brunt-Vaisala frequency^2 [1/s^2]"),
    /* 139 */ Parm("PVMW", "Potential vorticity (mass-weighted) [1/s/m]"),
    /* 140 */ Parm("CRAIN", "Categorical rain [yes=1;no=0]"),
    /* 141 */ Parm("CFRZR", "Categorical freezing rain [yes=1;no=0]"),
    /* 142 */ Parm("CICEP", "Categorical ice pellets [yes=1;no=0]"),
    /* 143 */ Parm("CSNOW", "Categorical snow [yes=1;no=0]"),
    /* 144 */ Parm("SOILW", "Volumetric soil moisture [fraction]"),
    /* 145 */ Parm("PEVPR", "Potential evaporation rate [W/m^2]"),
    /* 146 */ Parm("CWORK", "Cloud work function [J/kg]"),
    /* 147 */ Parm("U-GWD", "Zonal gravity wave stress [N/m^2]"),
    /* 148 */ Parm("V-GWD", "Meridional gravity wave stress [N/m^2]"),
    /* 149 */ Parm("PV", "Potential vorticity [m^2/s/kg]"),
    /* 150 */ Parm("COVMZ", "Covariance between u and v [m^2/s^2]"),
    /* 151 */ Parm("COVTZ", "Covariance between u and T [K*m/s]"),
    /* 152 */ Parm("COVTM", "Covariance between v and T [K*m/s]"),
    /* 153 */ Parm("CLWMR", "Cloud water [kg/kg]"),
    /* 154 */ Parm("O3MR", "Ozone mixing ratio [kg/kg]"),
    /* 155 */ Parm("GFLUX", "Ground heat flux [W/m^2]"),
    /* 156 */ Parm("CIN", "Convective inhibition [J/kg]"),
    /* 157 */ Parm("CAPE", "Convective Avail. Pot. Energy [J/kg]"),
    /* 158 */ Parm("TKE", "Turbulent kinetic energy [J/kg]"),
    /* 159 */ Parm("CONDP", "Lifted parcel condensation pressure [Pa]"),
    /* 160 */ Parm("CSUSF", "Clear sky upward solar flux [W/m^2]"),
    /* 161 */ Parm("CSDSF", "Clear sky downward solar flux [W/m^2]"),
    /* 162 */ Parm("CSULF", "Clear sky upward long wave flux [W/m^2]"),
    /* 163 */ Parm("CSDLF", "Clear sky downward long wave flux [W/m^2]"),
    /* 164 */ Parm("CFNSF", "Cloud forcing net solar flux [W/m^2]"),
    /* 165 */ Parm("CFNLF", "Cloud forcing net long wave flux [W/m^2]"),
    /* 166 */ Parm("VBDSF", "Visible beam downward solar flux [W/m^2]"),
    /* 167 */ Parm("VDDSF", "Visible diffuse downward solar flux [W/m^2]"),
    /* 168 */ Parm("NBDSF", "Near IR beam downward solar flux [W/m^2]"),
    /* 169 */ Parm("NDDSF", "Near IR diffuse downward solar flux [W/m^2]"),
    /* 170 */ Parm("RWMR", "Rain water mixing ratio [kg/kg]"),
    /* 171 */ Parm("SNMR", "Snow mixing ratio [kg/kg]"),
    /* 172 */ Parm("MFLX", "Momentum flux [N/m^2]"),
    /* 173 */ Parm("LMH", "Mass point model surface [non-dim]"),
    /* 174 */ Parm("LMV", "Velocity point model surface [non-dim]"),
    /* 175 */ Parm("MLYNO", "Model layer number (from bottom up) [non-dim]"),
    /* 176 */ Parm("NLAT", "Latitude (-90 to +90) [deg]"),
    /* 177 */ Parm("ELON", "East longitude (0-360) [deg]"),
    /* 178 */ Parm("ICMR", "Ice mixing ratio [kg/kg]"),
    /* 179 */ Parm("GRMR", "Graupel mixing ratio [kg/kg]"),
    /* 180 */ Parm("GUST", "Surface wind gust [m/s]"),
    /* 181 */ Parm("LPSX", "x-gradient of log pressure [1/m]"),
    /* 182 */ Parm("LPSY", "y-gradient of log pressure [1/m]"),
    /* 183 */ Parm("HGTX", "x-gradient of height [m/m]"),
    /* 184 */ Parm("HGTY", "y-gradient of height [m/m]"),
    /* 185 */ Parm("TURB", "Turbulence SIGMET/AIRMET [non-dim]"),
    /* 186 */ Parm("ICNG", "Icing SIGMET/AIRMET [non-dim]"),
    /* 187 */ Parm("LTNG", "Lightning [non-dim]"),
    /* 188 */ Parm("DRIP", "Rate of water dropping from canopy to gnd [kg/m^2]"),
    /* 189 */ Parm("VPTMP", "Virtual pot. temp. [K]"),
    /* 190 */ Parm("HLCY", "Storm relative helicity [m^2/s^2]"),
    /* 191 */ Parm("PROB", "Prob. from ensemble [non-dim]"),
    /* 192 */
    Parm(
        "PROBN",
        "Prob. from ensemble norm. to clim. expect. [non-dim]",
    ),
    /* 193 */ Parm("POP", "Prob. of precipitation [%]"),
    /* 194 */ Parm("CPOFP", "Prob. of frozen precipitation [%]"),
    /* 195 */ Parm("CPOZP", "Prob. of freezing precipitation [%]"),
    /* 196 */ Parm("USTM", "u-component of storm motion [m/s]"),
    /* 197 */ Parm("VSTM", "v-component of storm motion [m/s]"),
    /* 198 */ Parm("NCIP", "No. concen. ice particles []"),
    /* 199 */ Parm("EVBS", "Direct evaporation from bare soil [W/m^2]"),
    /* 200 */ Parm("EVCW", "Canopy water evaporation [W/m^2]"),
    /* 201 */ Parm("ICWAT", "Ice-free water surface [%]"),
    /* 202 */ Parm("CWDI", "Convective weather detection index []"),
    /* 203 */ Parm("VAFTAD", "VAFTAD?? [??]"),
    /* 204 */ Parm("DSWRF", "Downward short wave flux [W/m^2]"),
    /* 205 */ Parm("DLWRF", "Downward long wave flux [W/m^2]"),
    /* 206 */ Parm("UVI", "Ultraviolet index [W/m^2]"),
    /* 207 */ Parm("MSTAV", "Moisture availability [%]"),
    /* 208 */ Parm("SFEXC", "Exchange coefficient [(kg/m^3)(m/s)]"),
    /* 209 */ Parm("MIXLY", "No. of mixed layers next to surface [integer]"),
    /* 210 */ Parm("TRANS", "Transpiration [W/m^2]"),
    /* 211 */ Parm("USWRF", "Upward short wave flux [W/m^2]"),
    /* 212 */ Parm("ULWRF", "Upward long wave flux [W/m^2]"),
    /* 213 */ Parm("CDLYR", "Non-convective cloud [%]"),
    /* 214 */ Parm("CPRAT", "Convective precip. rate [kg/m^2/s]"),
    /* 215 */ Parm("TTDIA", "Temp. tendency by all physics [K/s]"),
    /* 216 */ Parm("TTRAD", "Temp. tendency by all radiation [K/s]"),
    /* 217 */ Parm("TTPHY", "Temp. tendency by non-radiation physics [K/s]"),
    /* 218 */ Parm("PREIX", "Precip index (0.0-1.00) [fraction]"),
    /* 219 */ Parm("TSD1D", "Std. dev. of IR T over 1x1 deg area [K]"),
    /* 220 */ Parm("NLGSP", "Natural log of surface pressure [ln(kPa)]"),
    /* 221 */ Parm("HPBL", "Planetary boundary layer height [m]"),
    /* 222 */ Parm("5WAVH", "5-wave geopotential height [gpm]"),
    /* 223 */ Parm("CNWAT", "Plant canopy surface water [kg/m^2]"),
    /* 224 */ Parm("SOTYP", "Soil type (Zobler) [0..9]"),
    /* 225 */ Parm("VGTYP", "Vegetation type (as in SiB) [0..13]"),
    /* 226 */ Parm("BMIXL", "Blackadar's mixing length scale [m]"),
    /* 227 */ Parm("AMIXL", "Asymptotic mixing length scale [m]"),
    /* 228 */ Parm("PEVAP", "Pot. evaporation [kg/m^2]"),
    /* 229 */ Parm("SNOHF", "Snow phase-change heat flux [W/m^2]"),
    /* 230 */ Parm("5WAVA", "5-wave geopot. height anomaly [gpm]"),
    /* 231 */ Parm("MFLUX", "Convective cloud mass flux [Pa/s]"),
    /* 232 */ Parm("DTRF", "Downward total radiation flux [W/m^2]"),
    /* 233 */ Parm("UTRF", "Upward total radiation flux [W/m^2]"),
    /* 234 */ Parm("BGRUN", "Baseflow-groundwater runoff [kg/m^2]"),
    /* 235 */ Parm("SSRUN", "Storm surface runoff [kg/m^2]"),
    /* 236 */
    Parm(
        "SIPD",
        "Supercooled large droplet (SLD) icing pot. diagn. []",
    ),
    /* 237 */ Parm("O3TOT", "Total ozone [kg/m^2]"),
    /* 238 */ Parm("SNOWC", "Snow cover [%]"),
    /* 239 */ Parm("SNOT", "Snow temp. [K]"),
    /* 240 */ Parm("COVTW", "Covariance T and w [K*m/s]"),
    /* 241 */ Parm("LRGHR", "Large scale condensation heating [K/s]"),
    /* 242 */ Parm("CNVHR", "Deep convective heating [K/s]"),
    /* 243 */ Parm("CNVMR", "Deep convective moistening [kg/kg/s]"),
    /* 244 */ Parm("SHAHR", "Shallow convective heating [K/s]"),
    /* 245 */ Parm("SHAMR", "Shallow convective moistening [kg/kg/s]"),
    /* 246 */ Parm("VDFHR", "Vertical diffusion heating [K/s]"),
    /* 247 */ Parm("VDFUA", "Vertical diffusion zonal accel [m/s^2]"),
    /* 248 */ Parm("VDFVA", "Vertical diffusion meridional accel [m/s^2]"),
    /* 249 */ Parm("VDFMR", "Vertical diffusion moistening [kg/kg/s]"),
    /* 250 */ Parm("SWHR", "Solar radiative heating [K/s]"),
    /* 251 */ Parm("LWHR", "Longwave radiative heating [K/s]"),
    /* 252 */ Parm("CD", "Drag coefficient [non-dim]"),
    /* 253 */ Parm("FRICV", "Friction velocity [m/s]"),
    /* 254 */ Parm("RI", "Richardson number [non-dim]"),
    /* 255 */ Parm("var255", "undefined"),
];
