use super::Parm;
pub const ECMWF_160: [Parm; 256] = [
    /* 0 */ Parm("var0", "undefined"),
    /* 1 */ Parm("var1", "undefined"),
    /* 2 */ Parm("var2", "undefined"),
    /* 3 */ Parm("var3", "undefined"),
    /* 4 */ Parm("var4", "undefined"),
    /* 5 */ Parm("var5", "undefined"),
    /* 6 */ Parm("var6", "undefined"),
    /* 7 */ Parm("var7", "undefined"),
    /* 8 */ Parm("var8", "undefined"),
    /* 9 */ Parm("var9", "undefined"),
    /* 10 */ Parm("var10", "undefined"),
    /* 11 */ Parm("var11", "undefined"),
    /* 12 */ Parm("var12", "undefined"),
    /* 13 */ Parm("var13", "undefined"),
    /* 14 */ Parm("var14", "undefined"),
    /* 15 */ Parm("var15", "undefined"),
    /* 16 */ Parm("var16", "undefined"),
    /* 17 */ Parm("var17", "undefined"),
    /* 18 */ Parm("var18", "undefined"),
    /* 19 */ Parm("var19", "undefined"),
    /* 20 */ Parm("var20", "undefined"),
    /* 21 */ Parm("var21", "undefined"),
    /* 22 */ Parm("var22", "undefined"),
    /* 23 */ Parm("var23", "undefined"),
    /* 24 */ Parm("var24", "undefined"),
    /* 25 */ Parm("var25", "undefined"),
    /* 26 */ Parm("var26", "undefined"),
    /* 27 */ Parm("var27", "undefined"),
    /* 28 */ Parm("var28", "undefined"),
    /* 29 */ Parm("var29", "undefined"),
    /* 30 */ Parm("var30", "undefined"),
    /* 31 */ Parm("var31", "undefined"),
    /* 32 */ Parm("var32", "undefined"),
    /* 33 */ Parm("var33", "undefined"),
    /* 34 */ Parm("var34", "undefined"),
    /* 35 */ Parm("var35", "undefined"),
    /* 36 */ Parm("var36", "undefined"),
    /* 37 */ Parm("var37", "undefined"),
    /* 38 */ Parm("var38", "undefined"),
    /* 39 */ Parm("var39", "undefined"),
    /* 40 */ Parm("var40", "undefined"),
    /* 41 */ Parm("var41", "undefined"),
    /* 42 */ Parm("var42", "undefined"),
    /* 43 */ Parm("var43", "undefined"),
    /* 44 */ Parm("var44", "undefined"),
    /* 45 */ Parm("var45", "undefined"),
    /* 46 */ Parm("var46", "undefined"),
    /* 47 */ Parm("var47", "undefined"),
    /* 48 */ Parm("var48", "undefined"),
    /* 49 */ Parm("10FG", "10 metre wind gust during averaging time [m s**-1]"),
    /* 50 */ Parm("var50", "undefined"),
    /* 51 */ Parm("var51", "undefined"),
    /* 52 */ Parm("var52", "undefined"),
    /* 53 */ Parm("var53", "undefined"),
    /* 54 */ Parm("var54", "undefined"),
    /* 55 */ Parm("var55", "undefined"),
    /* 56 */ Parm("var56", "undefined"),
    /* 57 */ Parm("var57", "undefined"),
    /* 58 */ Parm("var58", "undefined"),
    /* 59 */ Parm("var59", "undefined"),
    /* 60 */ Parm("var60", "undefined"),
    /* 61 */ Parm("var61", "undefined"),
    /* 62 */ Parm("var62", "undefined"),
    /* 63 */ Parm("var63", "undefined"),
    /* 64 */ Parm("var64", "undefined"),
    /* 65 */ Parm("var65", "undefined"),
    /* 66 */ Parm("var66", "undefined"),
    /* 67 */ Parm("var67", "undefined"),
    /* 68 */ Parm("var68", "undefined"),
    /* 69 */ Parm("var69", "undefined"),
    /* 70 */ Parm("var70", "undefined"),
    /* 71 */ Parm("var71", "undefined"),
    /* 72 */ Parm("var72", "undefined"),
    /* 73 */ Parm("var73", "undefined"),
    /* 74 */ Parm("var74", "undefined"),
    /* 75 */ Parm("var75", "undefined"),
    /* 76 */ Parm("var76", "undefined"),
    /* 77 */ Parm("var77", "undefined"),
    /* 78 */ Parm("var78", "undefined"),
    /* 79 */ Parm("var79", "undefined"),
    /* 80 */ Parm("var80", "undefined"),
    /* 81 */ Parm("var81", "undefined"),
    /* 82 */ Parm("var82", "undefined"),
    /* 83 */ Parm("var83", "undefined"),
    /* 84 */ Parm("var84", "undefined"),
    /* 85 */ Parm("var85", "undefined"),
    /* 86 */ Parm("var86", "undefined"),
    /* 87 */ Parm("var87", "undefined"),
    /* 88 */ Parm("var88", "undefined"),
    /* 89 */ Parm("var89", "undefined"),
    /* 90 */ Parm("var90", "undefined"),
    /* 91 */ Parm("var91", "undefined"),
    /* 92 */ Parm("var92", "undefined"),
    /* 93 */ Parm("var93", "undefined"),
    /* 94 */ Parm("var94", "undefined"),
    /* 95 */ Parm("var95", "undefined"),
    /* 96 */ Parm("var96", "undefined"),
    /* 97 */ Parm("var97", "undefined"),
    /* 98 */ Parm("var98", "undefined"),
    /* 99 */ Parm("var99", "undefined"),
    /* 100 */ Parm("var100", "undefined"),
    /* 101 */ Parm("var101", "undefined"),
    /* 102 */ Parm("var102", "undefined"),
    /* 103 */ Parm("var103", "undefined"),
    /* 104 */ Parm("var104", "undefined"),
    /* 105 */ Parm("var105", "undefined"),
    /* 106 */ Parm("var106", "undefined"),
    /* 107 */ Parm("var107", "undefined"),
    /* 108 */ Parm("var108", "undefined"),
    /* 109 */ Parm("var109", "undefined"),
    /* 110 */ Parm("var110", "undefined"),
    /* 111 */ Parm("var111", "undefined"),
    /* 112 */ Parm("var112", "undefined"),
    /* 113 */ Parm("var113", "undefined"),
    /* 114 */ Parm("var114", "undefined"),
    /* 115 */ Parm("var115", "undefined"),
    /* 116 */ Parm("var116", "undefined"),
    /* 117 */ Parm("var117", "undefined"),
    /* 118 */ Parm("var118", "undefined"),
    /* 119 */ Parm("var119", "undefined"),
    /* 120 */ Parm("var120", "undefined"),
    /* 121 */ Parm("var121", "undefined"),
    /* 122 */ Parm("var122", "undefined"),
    /* 123 */ Parm("var123", "undefined"),
    /* 124 */ Parm("var124", "undefined"),
    /* 125 */ Parm("var125", "undefined"),
    /* 126 */ Parm("var126", "undefined"),
    /* 127 */ Parm("AT", "Atmospheric tide []"),
    /* 128 */ Parm("BV", "Budget values []"),
    /* 129 */ Parm("Z", "Geopotential [m**2 s**-2]"),
    /* 130 */ Parm("T", "Temperature [K]"),
    /* 131 */ Parm("U", "U velocity [m s**-1]"),
    /* 132 */ Parm("V", "V velocity [m s**-1]"),
    /* 133 */ Parm("Q", "Specific humidity [kg kg**-1]"),
    /* 134 */ Parm("SP", "Surface pressure [Pa]"),
    /* 135 */ Parm("W", "Vertical velocity [Pa s**-1]"),
    /* 136 */ Parm("TCW", "Total column water [kg m**-2]"),
    /* 137 */ Parm("PWC", "Precipitable water content [kg m**-2]"),
    /* 138 */ Parm("VO", "Vorticity (relative) [s**-1]"),
    /* 139 */ Parm("STL1", "Soil temperature level 1 [K]"),
    /* 140 */ Parm("SWL1", "Soil wetness level 1 [m]"),
    /* 141 */ Parm("SD", "Snow depth [m of water]"),
    /* 142 */ Parm("LSP", "Large-scale precipitation [kg m**-2 s**-1]"),
    /* 143 */ Parm("CP", "Convective precipitation [kg m**-2 s**-1]"),
    /* 144 */ Parm("SF", "Snowfall [kg m**-2 s**-1]"),
    /* 145 */ Parm("BLD", "Boundary layer dissipation [W m**-2]"),
    /* 146 */ Parm("SSHF", "Surface sensible heat flux [W m**-2]"),
    /* 147 */ Parm("SLHF", "Surface latent heat flux [W m**-2]"),
    /* 148 */ Parm("var148", "undefined"),
    /* 149 */ Parm("var149", "undefined"),
    /* 150 */ Parm("var150", "undefined"),
    /* 151 */ Parm("MSL", "Mean sea level pressure [Pa]"),
    /* 152 */ Parm("LNSP", "Logarithm of surface pressure []"),
    /* 153 */ Parm("var153", "undefined"),
    /* 154 */ Parm("var154", "undefined"),
    /* 155 */ Parm("D", "Divergence [s**-1]"),
    /* 156 */ Parm("GH", "Height [m]"),
    /* 157 */ Parm("R", "Relative humidity [(0 - 1)]"),
    /* 158 */ Parm("TSP", "Tendency of surface pressure [Pa s**-1]"),
    /* 159 */ Parm("var159", "undefined"),
    /* 160 */ Parm("var160", "undefined"),
    /* 161 */ Parm("var161", "undefined"),
    /* 162 */ Parm("var162", "undefined"),
    /* 163 */ Parm("var163", "undefined"),
    /* 164 */ Parm("TCC", "Total cloud cover [(0 - 1)]"),
    /* 165 */ Parm("10U", "10 metre U wind component [m s**-1]"),
    /* 166 */ Parm("10V", "10 metre V wind component [m s**-1]"),
    /* 167 */ Parm("2T", "2 metre temperature [K]"),
    /* 168 */ Parm("2D", "2 metre dewpoint temperature [K]"),
    /* 169 */ Parm("var169", "undefined"),
    /* 170 */ Parm("STL2", "Soil temperature level 2 [K]"),
    /* 171 */ Parm("SWL2", "Soil wetness level 2 [m]"),
    /* 172 */ Parm("LSM", "Land-sea mask [(0 - 1)]"),
    /* 173 */ Parm("SR", "Surface roughness [m]"),
    /* 174 */ Parm("AL", "Albedo [(0 - 1)]"),
    /* 175 */ Parm("var175", "undefined"),
    /* 176 */ Parm("SSR", "Surface solar radiation [W m**-2]"),
    /* 177 */ Parm("STR", "Surface thermal radiation [W m**-2]"),
    /* 178 */ Parm("TSR", "Top solar radiation [W m**-2]"),
    /* 179 */ Parm("TTR", "Top thermal radiation [W m**-2]"),
    /* 180 */ Parm("EWSS", "East-West surface stress [N m**-2 s**-1]"),
    /* 181 */ Parm("NSSS", "North-South surface stress [N m**-2 s**-1]"),
    /* 182 */ Parm("E", "Evaporation [kg m**-2 s**-1]"),
    /* 183 */ Parm("STL3", "Soil temperature level 3 [K]"),
    /* 184 */ Parm("SWL3", "Soil wetness level 3 [m]"),
    /* 185 */ Parm("CCC", "Convective cloud cover [(0 - 1)]"),
    /* 186 */ Parm("LCC", "Low cloud cover [(0 - 1)]"),
    /* 187 */ Parm("MCC", "Medium cloud cover [(0 - 1)]"),
    /* 188 */ Parm("HCC", "High cloud cover [(0 - 1)]"),
    /* 189 */ Parm("var189", "undefined"),
    /* 190 */
    Parm(
        "EWOV",
        "East-West component of sub-gridscale orographic variance [m**2]",
    ),
    /* 191 */
    Parm(
        "NSOV",
        "North-South component of sub-gridscale orographic variance [m**2]",
    ),
    /* 192 */
    Parm(
        "NWOV",
        "North-West/South-East component of sub-gridscale orographic variance [m**2]",
    ),
    /* 193 */
    Parm(
        "NEOV",
        "North-East/South-West component of sub-gridscale orographic variance [m**2]",
    ),
    /* 194 */ Parm("var194", "undefined"),
    /* 195 */
    Parm(
        "LGWS",
        "Latitudinal component of gravity wave stress [N m**-2 s]",
    ),
    /* 196 */
    Parm(
        "MGWS",
        "Meridional component of gravity wave stress [N m**-2 s]",
    ),
    /* 197 */ Parm("GWD", "Gravity wave dissipation [W m**-2 s]"),
    /* 198 */ Parm("SRC", "Skin reservoir content [m of water]"),
    /* 199 */ Parm("VEG", "Percentage of vegetation [%]"),
    /* 200 */ Parm("VSO", "Variance of sub-gridscale orography [m**2]"),
    /* 201 */
    Parm(
        "MX2T",
        "Maximum temperature at 2 metres during averaging time [K]",
    ),
    /* 202 */
    Parm(
        "MN2T",
        "Minimium temperature at 2 metres during averaging time [K]",
    ),
    /* 203 */ Parm("var203", "undefined"),
    /* 204 */ Parm("PAW", "Precipitation analysis weights []"),
    /* 205 */ Parm("RO", "Runoff [kg m**-2 s**-1]"),
    /* 206 */ Parm("ZZ", "Standard deviation of geopotential [m**2 s**-2]"),
    /* 207 */
    Parm(
        "TZ",
        "Covariance of temperature and geopotential [K m**2 s**-2]",
    ),
    /* 208 */ Parm("TT", "Standard deviation of temperature [K]"),
    /* 209 */
    Parm(
        "QZ",
        "Covariance of specific humidity and geopotential [m**2 s**-2]",
    ),
    /* 210 */ Parm("QT", "Covariance of specific humidity and temperature [K]"),
    /* 211 */ Parm("QQ", "Standard deviation of specific humidity [(0 - 1)]"),
    /* 212 */
    Parm(
        "UZ",
        "Covariance of U component and geopotential [m**3 s**-3]",
    ),
    /* 213 */
    Parm(
        "UT",
        "Covariance of U component and temperature [K m s**-1]",
    ),
    /* 214 */
    Parm(
        "UQ",
        "Covariance of U component and specific humidity [m s**-1]",
    ),
    /* 215 */ Parm("UU", "Standard deviation of U velocity [m s**-1]"),
    /* 216 */
    Parm(
        "VZ",
        "Covariance of V component and geopotential [m**3 s**-3]",
    ),
    /* 217 */
    Parm(
        "VT",
        "Covariance of V component and temperature [K m s**-1]",
    ),
    /* 218 */
    Parm(
        "VQ",
        "Covariance of V component and specific humidity [m s**-1]",
    ),
    /* 219 */
    Parm(
        "VU",
        "Covariance of V component and U component [m**2 s**-2]",
    ),
    /* 220 */ Parm("VV", "Standard deviation of V component [m s**-1]"),
    /* 221 */
    Parm(
        "WZ",
        "Covariance of W component and geopotential [Pa m**2 s**-3]",
    ),
    /* 222 */
    Parm(
        "WT",
        "Covariance of W component and temperature [K Pa s**-1]",
    ),
    /* 223 */
    Parm(
        "WQ",
        "Covariance of W component and specific humidity [Pa s**-1]",
    ),
    /* 224 */
    Parm(
        "WU",
        "Covariance of W component and U component [Pa m s**-2]",
    ),
    /* 225 */
    Parm(
        "WV",
        "Covariance of W component and V component [Pa m s**-2]",
    ),
    /* 226 */ Parm("WW", "Standard deviation of vertical velocity [Pa s**-1]"),
    /* 227 */ Parm("var227", "undefined"),
    /* 228 */ Parm("TP", "Total precipitation [m]"),
    /* 229 */ Parm("IEWS", "Instantaneous X surface stress [N m**-2]"),
    /* 230 */ Parm("INSS", "Instantaneous Y surface stress [N m**-2]"),
    /* 231 */ Parm("ISHF", "Instantaneous surface heat flux [W m**-2]"),
    /* 232 */ Parm("IE", "Instantaneous moisture flux [kg m**-2 s**-1]"),
    /* 233 */ Parm("ASQ", "Apparent surface humidity [kg kg**-1]"),
    /* 234 */ Parm("LSRH", "Logarithm of surface roughness length for heat []"),
    /* 235 */ Parm("SKT", "Skin temperature [K]"),
    /* 236 */ Parm("STL4", "Soil temperature level 4 [K]"),
    /* 237 */ Parm("SWL4", "Soil wetness level 4 [m]"),
    /* 238 */ Parm("TSN", "Temperature of snow layer [K]"),
    /* 239 */ Parm("CSF", "Convective snowfall [kg m**-2 s**-1]"),
    /* 240 */ Parm("LSF", "Large-scale snowfall [kg m**-2 s**-1]"),
    /* 241 */ Parm("CLWCER", "Cloud liquid water content [kg kg**-1]"),
    /* 242 */ Parm("CC", "Cloud cover [(0 - 1)]"),
    /* 243 */ Parm("FAL", "Forecast albedo []"),
    /* 244 */ Parm("FSR", "Forecast surface roughness [m]"),
    /* 245 */
    Parm(
        "FLSR",
        "Forecast logarithm of surface roughness for heat []",
    ),
    /* 246 */ Parm("10WS", "10 metre wind speed [m s**-1]"),
    /* 247 */ Parm("MOFL", "Momentum flux [N m**-2]"),
    /* 248 */ Parm("var248", "undefined"),
    /* 249 */ Parm("var249", "Gravity wave dissipation flux [W m**-2]"),
    /* 250 */ Parm("var250", "undefined"),
    /* 251 */ Parm("var251", "undefined"),
    /* 252 */ Parm("var252", "undefined"),
    /* 253 */ Parm("var253", "undefined"),
    /* 254 */ Parm("HSD", "Heaviside beta function [(0 - 1)]"),
    /* 255 */ Parm("var255", "Indicates a missing value []"),
];
